// This file is replaced by autobuild/atversionrc.h for final builds, generated by
// release.py.

#ifndef f_AT_ATVERSIONRC_H
#define f_AT_ATVERSIONRC_H

#define AT_WIN_VERSIONBLOCK_FILEVERSION 4,1,0,0
#define AT_WIN_VERSIONBLOCK_FILEVERSION_STR "4.1.0.0"
#define AT_WIN_VERSIONBLOCK_PRODUCTVERSION 4,1,0,0
#define AT_WIN_VERSIONBLOCK_PRODUCTVERSION_STR "4.1.0.0"

#endif
