//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Altirra.rc
//
#define IDC_NEXT                        3
#define IDR_DEBUGGER_MENU               102
#define IDR_DEBUGGER_ACCEL              103
#define IDD_CPU_OPTIONS                 104
#define IDD_DISK_DRIVES                 105
#define IDD_CREATE_DISK                 106
#define IDD_ABOUT                       108
#define IDR_SOURCE_CONTEXT_MENU         109
#define IDR_KERNEL                      110
#define IDR_CHANGES                     112
#define IDD_CHANGE_LOG                  113
#define IDD_HARD_DISK                   114
#define IDR_HLEKERNEL                   116
#define IDR_DISASM_CONTEXT_MENU         118
#define IDD_INPUT_MAPPINGS              119
#define IDD_INPUTMAP_EDIT               120
#define IDD_INPUTMAP_ADDMAPPING         121
#define IDD_AUDIO_OPTIONS               123
#define IDR_NOKERNEL                    124
#define IDR_BASIC                       125
#define IDD_TAPE_CONTROL                126
#define IDD_ADJUST_COLORS               127
#define IDR_COLOR_PRESETS_MENU          128
#define IDR_MEMORY_CONTEXT_MENU         129
#define IDB_TOOLBAR_PROFILER            130
#define IDR_PROFILE_MODE_MENU           131
#define IDI_APPICON                     132
#define IDD_VIDEO_RECORDING             133
#define IDD_KEYBOARD                    134
#define IDD_CARTRIDGE_MAPPER            135
#define IDR_5200KERNEL                  136
#define IDD_INPUTMAP_ADDCONTROLLER      136
#define IDR_NOCARTRIDGE                 138
#define IDD_INPUTMAP_REBIND             138
#define IDR_HISTORY_CONTEXT_MENU        139
#define IDD_SERIAL_PORTS                140
#define IDD_LIGHTPEN                    142
#define IDR_DEBUG_HELP                  143
#define IDD_CHEATER                     144
#define IDD_CHEAT_EDIT                  145
#define IDD_ROM_IMAGES                  146
#define IDD_PROGRAM_ERROR               147
#define IDD_DISK_EXPLORER               148
#define IDR_DISK_EXPLORER_CONTEXT_MENU  149
#define IDR_DISKLOADER128               150
#define IDD_VERIFIER                    150
#define IDD_PCLINK                      151
#define IDD_SPEED                       152
#define IDR_DEBUGDISPLAY_CONTEXT_MENU   153
#define IDR_NOHDBIOS                    154
#define IDD_SELECT_PHYSICAL_DISK        155
#define IDD_OPTIONS                     156
#define IDD_OPTIONS_DISPLAY             157
#define IDD_OPTIONS_ERRORS              158
#define IDD_OPTIONS_DISPLAY_MODE        159
#define IDD_PROGRESS                    160
#define IDD_OPTIONS_STARTUP             161
#define IDR_NOGAME                      162
#define IDD_FILE_ASSOC                  162
#define IDD_OPTIONS_FILEASSOC           163
#define IDR_ABOUT                       164
#define IDD_HDEVICE                     164
#define IDR_DISPLAY_CONTEXT_MENU        165
#define IDR_TRACK_STEP                  166
#define IDR_DISK_SPIN                   167
#define IDR_TRACK_STEP_2                168
#define IDR_MENU_DEFAULT                169
#define IDD_DIALOG1                     170
#define IDD_CONFIGURE_ACCEL             170
#define IDR_U1MBBIOS                    171
#define IDR_BOOTSECTOR_DOS2             172
#define IDD_CREATE_VHD                  173
#define IDR_KERNELXL                    174
#define IDC_CURSOR1                     175
#define IDC_TARGET_OFF                  175
#define IDR_DRAGDROP_MENU               176
#define IDR_DISK_CONTEXT_MENU           177
#define IDD_OPTIONS_FLASH               178
#define IDD_DEBUG_CHOOSE_FONT           179
#define IDI_DISK                        500
#define IDI_TAPE                        501
#define IDI_XEX                         502
#define IDI_CART                        503
#define IDI_EJECT                       520
#define IDI_NEWDISK                     521
#define IDC_ENABLE_HISTORY              1001
#define IDC_ENABLE_PATHS                1002
#define IDC_DISKPATH1                   1002
#define IDC_BROWSE1                     1003
#define IDC_ENABLE_ILLEGALS             1003
#define IDC_STOP_ON_BRK                 1004
#define IDC_DISKPATH5                   1004
#define IDC_DISKPATH2                   1005
#define IDC_SECTOR_SIZE_128             1005
#define IDC_ALLOWNMIBLOCKING            1005
#define IDC_BROWSE10                    1005
#define IDC_BROWSE2                     1006
#define IDC_SECTOR_SIZE_256             1006
#define IDC_SHADOW_ROM                  1006
#define IDC_SECTOR_COUNT                1007
#define IDC_BROWSE5                     1007
#define IDC_SHADOW_CARTS                1007
#define IDC_DISKPATH3                   1008
#define IDC_BOOT_SECTOR_COUNT           1008
#define IDC_BROWSE3                     1009
#define IDC_SECTOR_SIZE_512             1009
#define IDC_WRITEMODE1                  1010
#define IDC_DISKPATH4                   1011
#define IDC_BROWSE4                     1012
#define IDC_WRITEMODE2                  1013
#define IDC_TEXT                        1013
#define IDC_EJECT1                      1014
#define IDC_PATH                        1014
#define IDC_EJECT2                      1015
#define IDC_BROWSE                      1015
#define IDC_EJECT3                      1016
#define IDC_READONLY                    1016
#define IDC_EJECT4                      1017
#define IDC_ENABLE                      1017
#define IDC_NEWDISK1                    1018
#define IDC_CPUMODEL_6502C              1018
#define IDC_BURSTIO                     1018
#define IDC_MORE1                       1018
#define IDC_NEWDISK2                    1019
#define IDC_CPUMODEL_65C02              1019
#define IDC_MORE2                       1019
#define IDC_NEWDISK3                    1020
#define IDC_CPUMODEL_65C816             1020
#define IDC_LIST                        1020
#define IDC_VC_ZMBV                     1020
#define IDC_RATE_INTEGRAL               1020
#define IDC_ERRORMODE_PAUSE             1020
#define IDC_MORE3                       1020
#define IDC_NEWDISK4                    1021
#define IDC_ADD                         1021
#define IDC_ERRORMODE_COLDRESET         1021
#define IDC_MORE4                       1021
#define IDC_CPUMODEL_65C816_7MHZ        1021
#define IDC_WRITEMODE3                  1022
#define IDC_DELETE                      1022
#define IDC_CPUMODEL_65C816_3MHZ        1022
#define IDC_SAVEAS1                     1023
#define IDC_ADD2                        1023
#define IDC_ADDCONTROLLER               1023
#define IDC_CPUMODEL_65C816_10MHZ       1023
#define IDC_SAVEAS2                     1024
#define IDC_RESET                       1024
#define IDC_CPUMODEL_65C816_14MHZ       1024
#define IDC_SAVEAS3                     1025
#define IDC_CLONE                       1025
#define IDC_SAVEAS4                     1026
#define IDC_SOURCE                      1026
#define IDC_PRESETS                     1026
#define IDC_WRITEMODE4                  1027
#define IDC_CONTROLLER                  1027
#define IDC_MODE                        1027
#define IDC_TARGET                      1028
#define IDC_VOLUME                      1028
#define IDC_SAVEAS5                     1028
#define IDC_PORT                        1029
#define IDC_STATIC_VOLUME               1029
#define IDC_WRITEMODE5                  1029
#define IDC_POSITION                    1030
#define IDC_NEWDISK5                    1030
#define IDC_LATENCY                     1030
#define IDC_MORE5                       1030
#define IDC_EJECT5                      1031
#define IDC_STATIC_LATENCY              1031
#define IDC_DISKPATH6                   1032
#define IDC_EXTRABUFFER                 1032
#define IDC_STATIC_POSITION             1033
#define IDC_BROWSE6                     1033
#define IDC_STATIC_EXTRABUFFER          1033
#define IDC_SAVEAS6                     1034
#define IDC_VOLUME2                     1034
#define IDC_DRIVEVOL                    1034
#define IDC_HUESTART                    1035
#define IDC_WRITEMODE6                  1035
#define IDC_STATIC_DRIVEVOL             1035
#define IDC_HUERANGE                    1036
#define IDC_NEWDISK6                    1036
#define IDC_MORE6                       1036
#define IDC_BRIGHTNESS                  1037
#define IDC_EJECT6                      1037
#define IDC_CONTRAST                    1038
#define IDC_DISKPATH7                   1038
#define IDC_SATURATION                  1039
#define IDC_BROWSE7                     1039
#define IDC_ARTPHASE                    1040
#define IDC_SAVEAS7                     1040
#define IDC_ARTSAT                      1041
#define IDC_WRITEMODE7                  1041
#define IDC_STATIC_HUESTART             1042
#define IDC_NEWDISK7                    1042
#define IDC_MORE7                       1042
#define IDC_STATIC_HUERANGE             1043
#define IDC_EJECT7                      1043
#define IDC_STATIC_BRIGHTNESS           1044
#define IDC_DISKPATH8                   1044
#define IDC_STATIC_CONTRAST             1045
#define IDC_BROWSE8                     1045
#define IDC_STATIC_SATURATION           1046
#define IDC_SAVEAS8                     1046
#define IDC_STATIC_ARTPHASE             1047
#define IDC_WRITEMODE8                  1047
#define IDC_STATIC_ARTSAT               1048
#define IDC_NEWDISK8                    1048
#define IDC_MORE8                       1048
#define IDC_ARTBRI                      1049
#define IDC_EJECT8                      1049
#define IDC_STATIC_ARTBRI               1050
#define IDC_EXPLORE1                    1050
#define IDC_EXPLORE2                    1051
#define IDC_LOADPRESET                  1052
#define IDC_EXPLORE3                    1052
#define IDC_EXPLORE4                    1053
#define IDC_COLORS                      1054
#define IDC_EXPLORE5                    1054
#define IDC_GAMEPAD                     1055
#define IDC_EXPLORE6                    1055
#define IDC_FORMAT                      1056
#define IDC_EXPLORE7                    1056
#define IDC_VC_NONE                     1057
#define IDC_EXPLORE8                    1057
#define IDC_VC_RLE                      1058
#define IDC_FOLDER1                     1058
#define IDC_KPMODE_COOKED               1059
#define IDC_FOLDER2                     1059
#define IDC_KPMODE_RAW                  1060
#define IDC_FOLDER3                     1060
#define IDC_FOLDER4                     1061
#define IDC_IDE_ENABLE                  1062
#define IDC_FOLDER5                     1062
#define IDC_IDE_IMAGEPATH               1063
#define IDC_FOLDER6                     1063
#define IDC_IDE_IMAGEBROWSE             1064
#define IDC_FOLDER7                     1064
#define IDC_IDEREADONLY                 1065
#define IDC_NEWDISK16                   1065
#define IDC_FOLDER8                     1065
#define IDC_STATIC_HOSTPATH             1068
#define IDC_STATIC_IDE_IMAGEPATH        1069
#define IDC_STATIC_IDE_IOREGION         1070
#define IDC_IDE_SIZE                    1071
#define IDC_STATIC_IDE_GEOMETRY         1072
#define IDC_STATIC_IDE_SIZE             1073
#define IDC_STATIC_IDE_SPEED            1074
#define IDC_IDE_CYLINDERS               1075
#define IDC_IDE_HEADS                   1076
#define IDC_IDE_SPT                     1077
#define IDC_STATIC_IDE_SPT              1078
#define IDC_STATIC_IDE_HEADS            1079
#define IDC_STATIC_IDE_CYLINDERS        1080
#define IDC_API_WAVEOUT                 1081
#define IDC_API_DIRECTSOUND             1082
#define IDC_DEBUG                       1083
#define IDC_TREE                        1084
#define IDC_IDE_DISKBROWSE              1084
#define IDC_ADDMAPPING                  1085
#define IDC_CREATE_VHD                  1085
#define IDC_EDIT                        1086
#define IDC_ADDDEFAULT                  1086
#define IDC_REBIND                      1087
#define IDC_STATIC_TARGET               1087
#define IDC_STOP                        1088
#define IDC_SPEED                       1089
#define IDC_STATIC_SPEED                1090
#define IDC_FLAG1                       1091
#define IDC_FLAG2                       1092
#define IDC_DRIVES1_8                   1093
#define IDC_DRIVES9_15                  1094
#define IDC_STATIC_D1                   1095
#define IDC_STATIC_D2                   1096
#define IDC_STATIC_D3                   1097
#define IDC_STATIC_D4                   1098
#define IDC_STATIC_D5                   1099
#define IDC_STATIC_D6                   1100
#define IDC_STATIC_D7                   1101
#define IDC_STATIC_D8                   1102
#define IDC_SPEED_FAST                  1103
#define IDC_SPEED_SLOW                  1104
#define IDC_RATE_BROADCAST              1104
#define IDC_ERRORMODE_DEBUG             1104
#define IDC_DEVICE_1030                 1104
#define IDC_STATIC_2600WARNING          1106
#define IDC_TELNET                      1107
#define IDC_VSPIN                       1108
#define IDC_ALLOW_OUTBOUND              1108
#define IDC_HSPIN                       1109
#define IDC_ACCEPT_IPV6                 1109
#define IDC_HVALUE                      1110
#define IDC_ACCEPT_IPV7                 1110
#define IDC_EXTENDED_BAUD_RATES         1110
#define IDC_VVALUE                      1111
#define IDC_RESULTS                     1111
#define IDC_TELNET_LFCONVERSION         1111
#define IDC_ACTIVE                      1112
#define IDC_DISABLE_THROTTLING          1112
#define IDC_VALUE                       1113
#define IDC_UPDATE                      1115
#define IDC_VT_8BIT                     1116
#define IDC_VT_16BIT                    1117
#define IDC_LOAD                        1118
#define IDC_SAVE                        1119
#define IDC_MODE_8BIT                   1120
#define IDC_MODE_16BIT                  1121
#define IDC_ADDRESS                     1123
#define IDC_TRANSFER                    1126
#define IDC_TRANSFERALL                 1127
#define IDC_FRAMERATE_NORMAL            1133
#define IDC_FRAMERATE_NTSCRATIO         1134
#define IDC_FRAMERATE_INTEGRAL          1135
#define IDC_HALF_RATE                   1136
#define IDC_CHANGE_VIDEO                1136
#define IDC_PALQUIRKS                   1136
#define IDC_ACCEPT_CONNECTIONS          1136
#define IDC_RESETSHIFT                  1136
#define IDC_GRAPHICS_DDRAW              1136
#define IDC_SINGLE_INSTANCE             1136
#define IDC_ENCODELONGNAMES             1136
#define IDC_CHANGE_FIRMWARE             1137
#define IDC_GRAPHICS_D3D9               1137
#define IDC_ENABLE_FKEYS                1137
#define IDC_CHANGE_BASIC                1138
#define IDC_GRAPHICS_OPENGL             1138
#define IDC_CHANGE_CPU                  1139
#define IDC_DISK_CONTENTS               1139
#define IDC_GRAPHICS_3D                 1139
#define IDC_CHANGE_DEBUGGING            1140
#define IDC_FILENAME                    1140
#define IDC_CHANGE_MEMORY               1141
#define IDC_SHARED                      1141
#define IDC_CHANGE_HARDWARE             1142
#define IDC_CHANGE_DISKIO               1143
#define IDC_STATUS                      1143
#define IDC_LISTEN_PORT                 1144
#define IDC_CONNECTION_SPEED            1146
#define IDC_REQUIRE_MATCHED_DTE_RATE    1147
#define IDC_FLAG_UNDOCOSENTRY           1148
#define IDC_FLAG_RECURSIVENMI           1149
#define IDC_FLAG_INTERRUPTREGS          1150
#define IDC_ALLOW_WRITES                1151
#define IDC_FLAG_WRAP64K                1151
#define IDC_ALLOW_WRITES2               1152
#define IDC_FLAG_ABNORMALDMA            1152
#define IDC_ARROWKEYMODE                1153
#define IDC_RATE_HARDWARE               1154
#define IDC_SPEED_ADJUST                1155
#define IDC_STATIC_SPEED_ADJUST         1156
#define IDC_EXPORT                      1157
#define IDC_PAGE_LIST                   1159
#define IDC_PAGE_AREA                   1160
#define IDC_HELP_INFO                   1161
#define IDC_ERRORMODE_DIALOG            1163
#define IDC_FSMODE_DESKTOP              1164
#define IDC_FSMODE_CUSTOM               1165
#define IDC_FSMODE_WIDTH                1166
#define IDC_FSMODE_HEIGHT               1167
#define IDC_FSMODE_REFRESH              1168
#define IDC_MODE_LIST                   1170
#define IDC_FSMODE_BROWSE               1171
#define IDC_SIOLEVEL_NONE               1172
#define IDC_SIOLEVEL_STUBLOADER         1173
#define IDC_STATIC_SIOLEVEL             1174
#define IDC_PROGRESS                    1175
#define IDC_STATIC_STATUS               1176
#define IDC_STATIC_DESC                 1177
#define IDC_LIST1                       1178
#define IDC_SETFILEASSOC                1179
#define IDC_REMOVEFILEASSOC             1180
#define IDC_DIAL_ADDRESS                1180
#define IDC_EMULATION_LEVEL             1181
#define IDC_DIAL_SERVICE                1181
#define IDC_DEVICE_850                  1182
#define IDC_STATIC_BAUDRATE             1183
#define IDC_STATIC_PERMISSIONS          1184
#define IDC_STATIC_PROTOCOL             1185
#define IDC_STATIC_DEVICE               1186
#define IDC_STATIC_DIAL_ADDRESS         1187
#define IDC_STATIC_DIAL_SERVICE         1188
#define IDC_STATIC_HOSTPATH1            1189
#define IDC_PATH1                       1190
#define IDC_STATIC_HOSTPATH2            1191
#define IDC_PATH2                       1192
#define IDC_STATIC_HOSTPATH3            1193
#define IDC_PATH3                       1194
#define IDC_STATIC_HOSTPATH4            1195
#define IDC_PATH4                       1196
#define IDC_HW_MODE                     1197
#define IDC_COMBO1                      1198
#define IDC_FILESYSTEM                  1198
#define IDC_SIC_FLASH                   1198
#define IDC_TYPE_FIXED                  1199
#define IDC_TYPE_DYNAMIC                1200
#define IDC_SIZE_SECTORS                1201
#define IDC_SIZE_MB                     1202
#define IDC_GEOMETRY_AUTO               1203
#define IDC_GEOMETRY_MANUAL             1204
#define IDC_HEADS                       1205
#define IDC_SPT                         1206
#define IDC_STATIC_SPT                  1207
#define IDC_STATIC_HEADS                1208
#define IDC_FONT_SEL                    1211
#define IDC_SIZE_SEL                    1212
#define IDC_SIZE_LIST                   1213
#define IDC_STATIC_SAMPLETEXT           1214
#define IDC_FONT_LIST                   1215
#define IDC_CHECK1                      1217
#define IDC_ENCODE_ALL_FRAMES           1217
#define ID_FILTERMODE_POINT             40023
#define ID_FILTERMODE_BILINEAR          40024
#define ID_FILTERMODE_BICUBIC           40025
#define ID_DEBUG_TOGGLEBREAKPOINT       40051
#define ID_DEBUG_STEPINTO               40052
#define ID_DEBUG_STEPOUT                40053
#define ID_DEBUG_STEPOVER               40054
#define ID_DEBUG_RUN                    40055
#define ID_DEBUG_BREAK                  40056
#define ID_CONTEXT_GOTODISASSEMBLY      40103
#define ID_CONTEXT_SETNEXTSTATEMENT     40104
#define ID_CONTEXT_SHOWNEXTSTATEMENT    40138
#define ID_CONTEXT_TOGGLEBREAKPOINT     40139
#define ID_CONTEXT_GOTOSOURCE           40140
#define ID_COLORS_ALTERNATE             40218
#define ID_COLORS_AUTHENTICNTSC         40219
#define ID_CONTEXT_CLEARALL             40226
#define ID_CONTEXT_TOGGLEREADBREAKPOINT 40227
#define ID_CONTEXT_TOGGLEWRITEBREAKPOINT 40228
#define ID_PROFMODE_SAMPLEINSNS         40244
#define ID_PROFMODE_SAMPLEFNS           40246
#define ID_PROFMODE_SAMPLEBASIC         40248
#define ID_COLORS_G2F                   40291
#define ID_COLORS_OLIVIERPAL            40293
#define ID_HISTORYCONTEXTMENU_SHOWPCADDRESS 40306
#define ID_HISTORYCONTEXTMENU_SHOWREGISTERS 40307
#define ID_HISTORYCONTEXTMENU_SHOWFLAGS 40308
#define ID_HISTORYCONTEXTMENU_SHOWCODEBYTES 40309
#define ID_CONTEXT_SHOWCODEBYTES        40310
#define ID_CONTEXT_SHOWLABELS           40311
#define ID_HISTORYCONTEXTMENU_SHOWLABELS 40312
#define ID_COLORS_DEFAULTNTSC           40336
#define ID_COLORS_DEFAULTPAL            40338
#define ID_DISKEXP_DELETE               40338
#define ID_DISKEXP_RENAME               40340
#define ID_HISTORYCONTEXTMENU_COPYVISIBLETOCLIPBOARD 40349
#define ID_CONTEXT_FORCEUPDATE          40382
#define ID_PALETTE_CURRENTREGISTERVALUES 40384
#define ID_PALETTE_ANALYSIS             40386
#define ID_PROFMODE_CALLGRAPH           40388
#define ID_COLORS_1XNTSC                40406
#define ID_HISTORYCONTEXTMENU_COLLAPSELOOPS 40420
#define ID_HISTORYCONTEXTMENU_COLLAPSECALLS 40421
#define ID_HISTORYCONTEXTMENU_COLLAPSEINTERRUPTS 40422
#define ID_HISTORYCONTEXTMENU_SHOWBEAMPOSITION 40423
#define ID_HISTORYCONTEXTMENU_SHOWUNHALTEDCYCLES 40426
#define ID_HISTORYCONTEXTMENU_SETTIMESTAMPORIGIN 40427
#define ID_HISTORYCONTEXTMENU_RESETTIMESTAMPORIGIN 40429
#define ID_HISTORYCONTEXTMENU_SHOWCYCLES 40430
#define ID_HISTORYCONTEXTMENU_SHOWMICROSECONDS 40431
#define ID_DISPLAYCONTEXTMENU_COPY      40445
#define ID_DISPLAYCONTEXTMENU_PASTE     40446
#define ID_HISTORYCONTEXTMENU_SHOWSPECIALREGISTERS 40477
#define ID_BOOTIMAGE                    40478
#define ID_DRAGDROP_BOOTIMAGE           40479
#define ID_MOUNTIMAGE_CARTRIDGE         40480
#define ID_MOUNTIMAGE_D1                40481
#define ID_MOUNTIMAGE_D2                40482
#define ID_MOUNTIMAGE_D3                40483
#define ID_MOUNTIMAGE_D4                40484
#define ID_MOUNTIMAGE_D                 40485
#define ID_CONTEXT_NEWDISK              40486
#define ID_CONTEXT_MOUNTFOLDERASVIRTUALDOS2DISK 40487
#define ID_CONTEXT_MOUNTFOLDERASVIRTUALSPARTADOSDISK 40488
#define ID_CONTEXT_EXPLOREDISK          40489
#define ID_CONTEXT_MOUNTFOLDERDOS2      40490
#define ID_CONTEXT_MOUNTFOLDERSDFS      40491
#define ID_CONTEXT_SAVEDISK             40492
#define ID_CONTEXT_EXTRACTBOOTSECTORSFORVIRTUALDOS2DISK 40493
#define ID_CONTEXT_EXTRACTBOOTSECTORS   40494
#define ID_INPUT_PORT1_NONE             45000
#define ID_INPUT_PORT2_NONE             45100
#define ID_INPUT_PORT3_NONE             45200
#define ID_INPUT_PORT4_NONE             45300
#define ID_FILE_MRU_BASE                46000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         40495
#define _APS_NEXT_CONTROL_VALUE         1218
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
