//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Altirra.rc
//
#define IDC_NEXT                        3
#define IDCANCEL2                       3
#define IDC_FROM_FILE                   3
#define IDC_PREV                        4
#define IDC_NEXT2                       5
#define IDR_DEBUGGER_MENU               102
#define IDD_DISK_DRIVES                 105
#define IDD_CREATE_DISK                 106
#define IDD_ABOUT                       108
#define IDR_SOURCE_CONTEXT_MENU         109
#define IDR_KERNEL                      110
#define IDR_CHANGES                     112
#define IDD_CHANGE_LOG                  113
#define IDR_DISASM_CONTEXT_MENU         118
#define IDD_INPUT_MAPPINGS              119
#define IDD_INPUTMAP_EDIT               120
#define IDD_INPUTMAP_ADDMAPPING         121
#define IDD_AUDIO_OPTIONS               123
#define IDR_NOKERNEL                    124
#define IDR_BASIC                       125
#define IDD_TAPE_CONTROL                126
#define IDD_ADJUST_ARTIFACTING          127
#define IDR_MEMORY_CONTEXT_MENU         129
#define IDB_TOOLBAR_PROFILER            130
#define IDR_PROFILE_MODE_MENU           131
#define IDI_APPICON                     132
#define IDD_VIDEO_RECORDING             133
#define IDD_CARTRIDGE_MAPPER            135
#define IDR_5200KERNEL                  136
#define IDD_INPUTMAP_ADDCONTROLLER      136
#define IDR_NOCARTRIDGE                 138
#define IDD_INPUTMAP_REBIND             138
#define IDR_HISTORY_CONTEXT_MENU        139
#define IDD_SERIAL_PORTS                140
#define IDD_DEVICE_850                  140
#define IDD_LIGHTPEN                    142
#define IDR_DEBUG_HELP                  143
#define IDD_CHEATER                     144
#define IDD_CHEAT_EDIT                  145
#define IDD_ROM_IMAGES                  146
#define IDD_PROGRAM_ERROR               147
#define IDD_DISK_EXPLORER               148
#define IDR_DISK_EXPLORER_CONTEXT_MENU  149
#define IDR_DISKLOADER128               150
#define IDD_VERIFIER                    150
#define IDD_PCLINK                      151
#define IDR_DEBUGDISPLAY_CONTEXT_MENU   153
#define IDR_NOHDBIOS                    154
#define IDD_SELECT_PHYSICAL_DISK        155
#define IDD_OPTIONS                     156
#define IDD_OPTIONS_DISPLAY             157
#define IDD_OPTIONS_ERRORS              158
#define IDD_OPTIONS_DISPLAY_MODE        159
#define IDD_PROGRESS                    160
#define IDD_OPTIONS_STARTUP             161
#define IDR_NOGAME                      162
#define IDD_OPTIONS_FILEASSOC           163
#define IDR_ABOUT                       164
#define IDD_HDEVICE                     164
#define IDR_DISPLAY_CONTEXT_MENU        165
#define IDR_TRACK_STEP                  166
#define IDR_DISK_SPIN                   167
#define IDR_TRACK_STEP_2                168
#define IDR_MENU_DEFAULT                169
#define IDD_DIALOG1                     170
#define IDD_CONFIGURE_ACCEL             170
#define IDR_U1MBBIOS                    171
#define IDR_BOOTSECTOR_DOS2             172
#define IDD_CREATE_VHD                  173
#define IDR_KERNELXL                    174
#define IDC_CURSOR1                     175
#define IDC_TARGET_OFF                  175
#define IDR_DRAGDROP_MENU               176
#define IDR_DISK_CONTEXT_MENU           177
#define IDD_OPTIONS_FLASH               178
#define IDD_DEBUG_CHOOSE_FONT           179
#define IDD_DRAGONCART                  181
#define IDR_PRINTER_CONTEXT_MENU        182
#define IDR_850RELOCATOR                183
#define IDR_850HANDLER                  184
#define IDD_FIRMWARE                    185
#define IDD_FIRMWARE_EDIT               186
#define IDD_DIALOG2                     187
#define IDD_OPTIONS_UI                  187
#define IDD_DEVICE_NEW                  189
#define IDD_HARD_DISK1                  190
#define IDD_DEVICE_HARDDISK             190
#define IDD_DEVICE_BLACKBOX             192
#define IDD_DEVICE_MODEM                193
#define IDD_ADJUST_COLORS               194
#define IDD_FILEVIEW                    195
#define IDD_DEVICE_1030MODEM            196
#define IDR_KERNEL1                     196
#define IDR_1030HANDLER                 196
#define IDR_1030FIRMWARE                196
#define IDR_KERNEL2                     197
#define IDD_DEVICE_SX212                197
#define IDR_KERNEL3                     198
#define IDR_NOMIO                       199
#define IDR_NOBLACKBOX                  200
#define IDR_TRACK_STEP_3                201
#define IDD_DEVICE_VERONICA             202
#define IDD_DEVICE_SOUNDBOARD           203
#define IDD_INPUT_SETUP                 204
#define IDD_KEYBOARD_CUSTOMIZE          205
#define IDR_PROFILE_OPTIONS_MENU        206
#define IDD_PROFILER_BOUNDARYRULE       207
#define IDD_PROFILES                    208
#define IDD_PROFILE_CATEGORIES          209
#define IDD_OPTIONS_SETTINGS            210
#define IDD_DEVICE_POCKETMODEM          211
#define IDD_DEVICE_CORVUS               212
#define IDD_OPTIONS_MEDIA               213
#define IDD_DEVICE_VERONICA1            214
#define IDD_DEVICE_MYIDE2               214
#define IDD_DEVICE_DONGLE               215
#define IDD_WIZARD                      216
#define IDD_WIZARD_SELECTTYPE           218
#define IDD_COMPATDB_EDITOR             219
#define IDD_COMPATDB_ADDTAG             220
#define IDD_COMPATDB_EDITALIAS          221
#define IDD_COMPATIBILITY               222
#define IDR_COMPATDB                    223
#define IDR_COMPATDBEDITOR_MENU         224
#define IDR_ROMSETREADME                225
#define IDR_COMPATDBEDITOR_ACCEL        226
#define IDD_DEVICE_DISKDRIVEFULL        227
#define IDR_MENU1                       228
#define IDR_PROFILE_LIST_CONTEXT_MENU   228
#define IDD_DEVICE_VBXE                 229
#define IDR_RAPIDUSFLASH                229
#define IDD_TRACEVIEWER                 230
#define IDR_RAPIDUSPBI16                230
#define IDB_TOOLBAR_TRACEVIEWER         231
#define IDD_TRACE_SETTINGS              232
#define IDB_TOOLBAR_PROFILER2           233
#define IDD_DIALOG3                     234
#define IDD_CMDLINEHELP                 234
#define IDR_CMDLINEHELP                 235
#define IDR_KERNEL816                   236
#define IDB_WARNING                     237
#define IDR_MENU2                       238
#define IDR_DISKEXPLORER_MENU           238
#define IDR_ADJUSTCOLORS_MENU           239
#define IDD_DEBUG_OPESOURCEFILE         240
#define IDD_DEBUG_OPENSOURCEFILE        240
#define IDD_DIALOG4                     241
#define IDD_ADJUST_COLORS_REFERENCE     241
#define IDD_DIALOG5                     242
#define IDD_DEBUG_MEMORYCTL             242
#define IDD_CREATEINPUTMAP              243
#define IDD_ADVANCED_CONFIGURATION      244
#define IDD_EDIT_VAR                    245
#define IDD_DEVICE_SIDE3                246
#define IDR_CUSTOMIZE_MENU              247
#define IDD_DIALOG6                     248
#define IDD_TAPEEDITOR                  248
#define IDR_TAPEEDITOR_ACCEL            249
#define IDR_TAPEEDITOR_MENU             250
#define IDD_CHECKFORUPDATES             251
#define IDD_CFGPROP_PATH                252
#define IDR_STUFF1                      253
#define IDR_SPEAKER_STEP                253
#define IDD_DIALOG7                     254
#define IDD_DBG_BREAKPOINTS             254
#define IDR_BREAKPOINT_CONTEXT_MENU     255
#define IDD_DEBUG_BREAKPOINT            256
#define IDR_MENU3                       257
#define IDR_PERFANALYZER_MENU           257
#define IDD_FILE_ASSOC2                 258
#define IDR_ACCELERATOR1                259
#define IDR_DEVICES_ACCEL               259
#define IDR_DEBUG_HELP_TEMPLATE         260
#define IDR_1030RELAY                   261
#define IDI_DISK                        500
#define IDI_TAPE                        501
#define IDI_XEX                         502
#define IDI_CART                        503
#define IDI_EJECT                       520
#define IDI_NEWDISK                     521
#define IDI_EJECT2                      522
#define IDC_ENABLE_HISTORY              1001
#define IDC_ENABLE_PATHS                1002
#define IDC_DISKPATH1                   1002
#define IDC_BROWSE1                     1003
#define IDC_ENABLE_ILLEGALS             1003
#define IDC_STOP_ON_BRK                 1004
#define IDC_DISKPATH5                   1004
#define IDC_DISKPATH2                   1005
#define IDC_SECTOR_SIZE_128             1005
#define IDC_ALLOWNMIBLOCKING            1005
#define IDC_BROWSE10                    1005
#define IDC_BROWSE2                     1006
#define IDC_SECTOR_SIZE_256             1006
#define IDC_SHADOW_ROM                  1006
#define IDC_SECTOR_COUNT                1007
#define IDC_BROWSE5                     1007
#define IDC_SHADOW_CARTS                1007
#define IDC_DISKPATH3                   1008
#define IDC_BOOT_SECTOR_COUNT           1008
#define IDC_LSTICKVIEW                  1008
#define IDC_BROWSE3                     1009
#define IDC_SECTOR_SIZE_512             1009
#define IDC_RSTICKVIEW                  1009
#define IDC_WRITEMODE1                  1010
#define IDC_LTRIGVIEW                   1010
#define IDC_DISKPATH4                   1011
#define IDC_RTRIGVIEW                   1011
#define IDC_BROWSE4                     1012
#define IDC_WRITEMODE2                  1013
#define IDC_TEXT                        1013
#define IDC_EJECT1                      1014
#define IDC_PATH                        1014
#define IDC_EJECT2                      1015
#define IDC_BROWSE                      1015
#define IDC_CRC32                       1015
#define IDC_PATH5                       1015
#define IDC_EJECT3                      1016
#define IDC_READONLY                    1016
#define IDC_PATH_PARENT                 1016
#define IDC_EJECT4                      1017
#define IDC_ENABLE                      1017
#define IDC_BROWSE_PARENT               1017
#define IDC_NEWDISK1                    1018
#define IDC_CPUMODEL_6502C              1018
#define IDC_BURSTIO                     1018
#define IDC_MORE1                       1018
#define IDC_NEWDISK2                    1019
#define IDC_CPUMODEL_65C02              1019
#define IDC_MORE2                       1019
#define IDC_NEWDISK3                    1020
#define IDC_CPUMODEL_65C816             1020
#define IDC_LIST                        1020
#define IDC_VC_ZMBV                     1020
#define IDC_RATE_INTEGRAL               1020
#define IDC_ERRORMODE_PAUSE             1020
#define IDC_MORE3                       1020
#define IDC_NEWDISK4                    1021
#define IDC_ADD                         1021
#define IDC_ERRORMODE_COLDRESET         1021
#define IDC_MORE4                       1021
#define IDC_CPUMODEL_65C816_7MHZ        1021
#define IDC_WRITEMODE3                  1022
#define IDC_DELETE                      1022
#define IDC_CPUMODEL_65C816_3MHZ        1022
#define IDC_ADD3                        1022
#define IDC_MORE                        1022
#define IDC_SAVEAS1                     1023
#define IDC_ADD2                        1023
#define IDC_ADDCONTROLLER               1023
#define IDC_CPUMODEL_65C816_10MHZ       1023
#define IDC_SAVEAS2                     1024
#define IDC_RESET                       1024
#define IDC_CPUMODEL_65C816_14MHZ       1024
#define IDC_SAVEAS3                     1025
#define IDC_CLONE                       1025
#define IDC_CPUMODEL_65C816_17MHZ       1025
#define IDC_SAVEAS4                     1026
#define IDC_SOURCE                      1026
#define IDC_PRESETS                     1026
#define IDC_CPUMODEL_65C816_14MHZ3      1026
#define IDC_CPUMODEL_65C816_21MHZ       1026
#define IDC_WRITEMODE4                  1027
#define IDC_CONTROLLER                  1027
#define IDC_MODE                        1027
#define IDC_TARGET                      1028
#define IDC_VOLUME                      1028
#define IDC_SAVEAS5                     1028
#define IDC_PORT                        1029
#define IDC_STATIC_VOLUME               1029
#define IDC_WRITEMODE5                  1029
#define IDC_POSITION                    1030
#define IDC_NEWDISK5                    1030
#define IDC_LATENCY                     1030
#define IDC_MORE5                       1030
#define IDC_BAUDRATE                    1030
#define IDC_EJECT5                      1031
#define IDC_STATIC_LATENCY              1031
#define IDC_DISKPATH6                   1032
#define IDC_EXTRABUFFER                 1032
#define IDC_STATIC_POSITION             1033
#define IDC_BROWSE6                     1033
#define IDC_STATIC_EXTRABUFFER          1033
#define IDC_SAVEAS6                     1034
#define IDC_VOLUME2                     1034
#define IDC_DRIVEVOL                    1034
#define IDC_HUESTART                    1035
#define IDC_WRITEMODE6                  1035
#define IDC_STATIC_DRIVEVOL             1035
#define IDC_HUERANGE                    1036
#define IDC_NEWDISK6                    1036
#define IDC_MORE6                       1036
#define IDC_COVOXVOL                    1036
#define IDC_BRIGHTNESS                  1037
#define IDC_EJECT6                      1037
#define IDC_STATIC_COVOXVOL             1037
#define IDC_CONTRAST                    1038
#define IDC_DISKPATH7                   1038
#define IDC_SATURATION                  1039
#define IDC_BROWSE7                     1039
#define IDC_ARTPHASE                    1040
#define IDC_SAVEAS7                     1040
#define IDC_ARTSAT                      1041
#define IDC_WRITEMODE7                  1041
#define IDC_STATIC_HUESTART             1042
#define IDC_NEWDISK7                    1042
#define IDC_MORE7                       1042
#define IDC_STATIC_HUERANGE             1043
#define IDC_EJECT7                      1043
#define IDC_STATIC_BRIGHTNESS           1044
#define IDC_DISKPATH8                   1044
#define IDC_STATIC_CONTRAST             1045
#define IDC_BROWSE8                     1045
#define IDC_STATIC_SATURATION           1046
#define IDC_SAVEAS8                     1046
#define IDC_STATIC_ARTPHASE             1047
#define IDC_WRITEMODE8                  1047
#define IDC_STATIC_ARTSAT               1048
#define IDC_NEWDISK8                    1048
#define IDC_MORE8                       1048
#define IDC_ARTBRI                      1049
#define IDC_EJECT8                      1049
#define IDC_ARTSHARP                    1049
#define IDC_STATIC_ARTBRI               1050
#define IDC_EXPLORE1                    1050
#define IDC_STATIC_ARTSHARP             1050
#define IDC_EXPLORE2                    1051
#define IDC_GAMMACORRECT                1051
#define IDC_LOADPRESET                  1052
#define IDC_EXPLORE3                    1052
#define IDC_EXPLORE4                    1053
#define IDC_STATIC_GAMMACORRECT         1053
#define IDC_COLORS                      1054
#define IDC_EXPLORE5                    1054
#define IDC_GAMEPAD                     1055
#define IDC_EXPLORE6                    1055
#define IDC_BLUE_INTENSITY              1055
#define IDC_RED_SHIFT                   1055
#define IDC_FORMAT                      1056
#define IDC_EXPLORE7                    1056
#define IDC_STATIC_BLUE_INTENSITY       1056
#define IDC_STATIC_RED_SHIFT            1056
#define IDC_VC_NONE                     1057
#define IDC_EXPLORE8                    1057
#define IDC_GREEN_INTENSITY             1057
#define IDC_RED_SCALE                   1057
#define IDC_VC_RLE                      1058
#define IDC_FOLDER1                     1058
#define IDC_STATIC_GREEN_INTENSITY      1058
#define IDC_STATIC_RED_SCALE            1058
#define IDC_KPMODE_COOKED               1059
#define IDC_FOLDER2                     1059
#define IDC_GREEN_ANGLE                 1059
#define IDC_GRN_SHIFT                   1059
#define IDC_KPMODE_RAW                  1060
#define IDC_FOLDER3                     1060
#define IDC_STATIC_GREEN_ANGLE          1060
#define IDC_STATIC_GRN_SHIFT            1060
#define IDC_FOLDER4                     1061
#define IDC_BLUE_ANGLE                  1061
#define IDC_GRN_SCALE                   1061
#define IDC_FOLDER5                     1062
#define IDC_STATIC_BLUE_ANGLE           1062
#define IDC_STATIC_GRN_SCALE            1062
#define IDC_IDE_IMAGEPATH               1063
#define IDC_FOLDER6                     1063
#define IDC_INTENSITYSCALE              1063
#define IDC_IDE_IMAGEBROWSE             1064
#define IDC_FOLDER7                     1064
#define IDC_STATIC_GAMMACORRECT2        1064
#define IDC_STATIC_INTENSITYSCALE       1064
#define IDC_IDEREADONLY                 1065
#define IDC_NEWDISK16                   1065
#define IDC_FOLDER8                     1065
#define IDC_BLU_SHIFT                   1067
#define IDC_STATIC_HOSTPATH             1068
#define IDC_STATIC_BLU_SHIFT            1068
#define IDC_STATIC_IDE_IMAGEPATH        1069
#define IDC_BLU_SCALE                   1069
#define IDC_STATIC_BLU_SCALE            1070
#define IDC_STATIC_IDE_IMAGEPATH2       1070
#define IDC_IDE_SIZE                    1071
#define IDC_STATIC_IDE_IMAGEPATH3       1071
#define IDC_STATIC_IDE_GEOMETRY         1072
#define IDC_STATIC_IDE_IMAGEPATH4       1072
#define IDC_STATIC_IDE_SIZE             1073
#define IDC_STATIC_IDE_IMAGEPATH5       1073
#define IDC_STATIC_IDE_SPEED            1074
#define IDC_STATIC_IDE_IMAGEPATH6       1074
#define IDC_IDE_CYLINDERS               1075
#define IDC_IDE_HEADS                   1076
#define IDC_IDE_SPT                     1077
#define IDC_STATIC_IDE_SPT              1078
#define IDC_STATIC_IDE_HEADS            1079
#define IDC_STATIC_IDE_CYLINDERS        1080
#define IDC_API_WAVEOUT                 1081
#define IDC_API_DIRECTSOUND             1082
#define IDC_DEBUG                       1083
#define IDC_TREE                        1084
#define IDC_IDE_DISKBROWSE              1084
#define IDC_ADDMAPPING                  1085
#define IDC_CREATE_VHD                  1085
#define IDC_EDIT                        1086
#define IDC_ADDDEFAULT                  1086
#define IDC_REBIND                      1087
#define IDC_STATIC_TARGET               1087
#define IDC_STOP                        1088
#define IDC_SPEED                       1089
#define IDC_STATIC_SPEED                1090
#define IDC_FLAG1                       1091
#define IDC_ACCEL                       1091
#define IDC_FLAG2                       1092
#define IDC_STATIC_ACCEL                1092
#define IDC_DRIVES1_8                   1093
#define IDC_DRIVES9_15                  1094
#define IDC_STATIC_D1                   1095
#define IDC_STATIC_D2                   1096
#define IDC_STATIC_D3                   1097
#define IDC_STATIC_D4                   1098
#define IDC_STATIC_D5                   1099
#define IDC_STATIC_D6                   1100
#define IDC_STATIC_D7                   1101
#define IDC_STATIC_D8                   1102
#define IDC_SPEED_FAST                  1103
#define IDC_SPEED_SLOW                  1104
#define IDC_RATE_BROADCAST              1104
#define IDC_ERRORMODE_DEBUG             1104
#define IDC_DEVICE_1030                 1104
#define IDC_STATIC_2600WARNING          1106
#define IDC_TELNET                      1107
#define IDC_VSPIN                       1108
#define IDC_ALLOW_OUTBOUND              1108
#define IDC_GUN_VSPIN                   1108
#define IDC_HSPIN                       1109
#define IDC_ACCEPT_IPV6                 1109
#define IDC_GUN_HSPIN                   1109
#define IDC_HVALUE                      1110
#define IDC_ACCEPT_IPV7                 1110
#define IDC_EXTENDED_BAUD_RATES         1110
#define IDC_GUN_HVALUE                  1110
#define IDC_VVALUE                      1111
#define IDC_RESULTS                     1111
#define IDC_TELNET_LFCONVERSION         1111
#define IDC_GUN_VVALUE                  1111
#define IDC_ACTIVE                      1112
#define IDC_DISABLE_THROTTLING          1112
#define IDC_PEN_HVALUE                  1112
#define IDC_VALUE                       1113
#define IDC_CONNECT_1200                1113
#define IDC_PEN_HSPIN                   1113
#define IDC_PEN_VVALUE                  1114
#define IDC_UPDATE                      1115
#define IDC_PEN_VSPIN                   1115
#define IDC_VT_8BIT                     1116
#define IDC_VT_16BIT                    1117
#define IDC_LOAD                        1118
#define IDC_SAVE                        1119
#define IDC_MODE_8BIT                   1120
#define IDC_MODE_16BIT                  1121
#define IDC_ADDRESS                     1123
#define IDC_ADDRESS2                    1124
#define IDC_TRANSFER                    1126
#define IDC_TRANSFERALL                 1127
#define IDC_FRAMERATE_NORMAL            1133
#define IDC_FRAMERATE_NTSCRATIO         1134
#define IDC_FRAMERATE_INTEGRAL          1135
#define IDC_HALF_RATE                   1136
#define IDC_CHANGE_VIDEO                1136
#define IDC_PALQUIRKS                   1136
#define IDC_ACCEPT_CONNECTIONS          1136
#define IDC_RESETSHIFT                  1136
#define IDC_GRAPHICS_DDRAW              1136
#define IDC_SINGLE_INSTANCE             1136
#define IDC_ENCODELONGNAMES             1136
#define IDC_CHANGE_FIRMWARE             1137
#define IDC_GRAPHICS_D3D9               1137
#define IDC_ENABLE_FKEYS                1137
#define IDC_ENCODELONGNAMES2            1137
#define IDC_LOWERCASENAMES              1137
#define IDC_CHANGE_BASIC                1138
#define IDC_GRAPHICS_OPENGL             1138
#define IDC_INSTALLASDISK               1138
#define IDC_ENABLE_FKEYS2               1138
#define IDC_ALLOW_INPUT_OVERLAP         1138
#define IDC_CHANGE_CPU                  1139
#define IDC_DISK_CONTENTS               1139
#define IDC_GRAPHICS_3D                 1139
#define IDC_ALLOW_INPUT_OVERLAP2        1139
#define IDC_ALLOW_INPUT_MODIFIER_OVERLAP 1139
#define IDC_CHANGE_DEBUGGING            1140
#define IDC_FILENAME                    1140
#define IDC_CHANGE_MEMORY               1141
#define IDC_SHARED                      1141
#define IDC_CHANGE_HARDWARE             1142
#define IDC_CHANGE_DISKIO               1143
#define IDC_STATUS                      1143
#define IDC_LISTEN_PORT                 1144
#define IDC_CONNECTION_SPEED            1146
#define IDC_REQUIRE_MATCHED_DTE_RATE    1147
#define IDC_FLAG_UNDOCOSENTRY           1148
#define IDC_CONNECTION_SPEED2           1148
#define IDC_NETWORKMODE                 1148
#define IDC_FLAG_RECURSIVENMI           1149
#define IDC_FLAG_INTERRUPTREGS          1150
#define IDC_ALLOW_WRITES                1151
#define IDC_FLAG_WRAP64K                1151
#define IDC_ALLOW_WRITES2               1152
#define IDC_FLAG_ABNORMALDMA            1152
#define IDC_USE_TIMESTAMPS              1152
#define IDC_SET_TIMESTAMPS              1152
#define IDC_ARROWKEYMODE                1153
#define IDC_RATE_HARDWARE               1154
#define IDC_SPEED_ADJUST                1155
#define IDC_STATIC_SPEED_ADJUST         1156
#define IDC_EXPORT                      1157
#define IDC_IMPORT                      1158
#define IDC_PAGE_LIST                   1159
#define IDC_COMPILE                     1159
#define IDC_PAGE_AREA                   1160
#define IDC_HELP_INFO                   1161
#define IDC_ERRORMODE_DIALOG            1163
#define IDC_FSMODE_DESKTOP              1164
#define IDC_FSMODE_CUSTOM               1165
#define IDC_FSMODE_WIDTH                1166
#define IDC_FSMODE_HEIGHT               1167
#define IDC_FSMODE_REFRESH              1168
#define IDC_FSMODE_DESKTOP2             1169
#define IDC_FSMODE_BORDERLESS           1169
#define IDC_MODE_LIST                   1170
#define IDC_FSMODE_BROWSE               1171
#define IDC_SIOLEVEL_NONE               1172
#define IDC_SIOLEVEL_STUBLOADER         1173
#define IDC_STATIC_SIOLEVEL             1174
#define IDC_PROGRESS                    1175
#define IDC_STATIC_STATUS               1176
#define IDC_STATIC_DESC                 1177
#define IDC_SETFILEASSOC                1179
#define IDC_REMOVEFILEASSOC             1180
#define IDC_DIAL_ADDRESS                1180
#define IDC_EMULATION_LEVEL             1181
#define IDC_DIAL_SERVICE                1181
#define IDC_SETUSERFILEASSOC            1181
#define IDC_DEVICE_850                  1182
#define IDC_REMOVEUSERFILEASSOC         1182
#define IDC_STATIC_BAUDRATE             1183
#define IDC_STATIC_PERMISSIONS          1184
#define IDC_STATIC_PROTOCOL             1185
#define IDC_STATIC_DEVICE               1186
#define IDC_STATIC_DIAL_ADDRESS         1187
#define IDC_STATIC_DIAL_SERVICE         1188
#define IDC_STATIC_HOSTPATH1            1189
#define IDC_STATIC_DIAL_ADDRESS2        1189
#define IDC_PATH1                       1190
#define IDC_STATIC_HOSTPATH2            1191
#define IDC_PATH2                       1192
#define IDC_STATIC_HOSTPATH3            1193
#define IDC_PATH3                       1194
#define IDC_STATIC_HOSTPATH4            1195
#define IDC_PATH4                       1196
#define IDC_STATIC_HOSTPATH5            1197
#define IDC_COMBO1                      1198
#define IDC_FILESYSTEM                  1198
#define IDC_SIC_FLASH                   1198
#define IDC_TERMINAL_TYPE               1198
#define IDC_LAYOUT                      1198
#define IDC_TYPE                        1198
#define IDC_RAM_SIZE                    1198
#define IDC_LINEWRAPMODE                1198
#define IDC_LUMA_RAMP                   1198
#define IDC_VIEWMODE                    1198
#define IDC_VERSION                     1198
#define IDC_REVISION                    1198
#define IDC_DRIVESELECT                 1198
#define IDC_SERIALPORT_SIGNAL1          1198
#define IDC_COREVERSION                 1198
#define IDC_VIDEO_RATE                  1198
#define IDC_TURBOTYPE                   1198
#define IDC_AUDIOAPI                    1198
#define IDC_SYMBOLLOAD_PRESTART         1198
#define IDC_VC                          1198
#define IDC_MONITORMODE                 1198
#define IDC_COLUMNS                     1198
#define IDC_CONTROLLERTYPE              1198
#define IDC_LFNMODE                     1198
#define IDC_NOISE_MODE                  1198
#define IDC_TYPE_FIXED                  1199
#define IDC_U1MB_FLASH                  1199
#define IDC_DEVICE_ID                   1199
#define IDC_SERIALPORT_SIGNAL2          1199
#define IDC_COMBO3                      1199
#define IDC_LUMA_RAMP2                  1199
#define IDC_COLORMATCHING_MODE          1199
#define IDC_SYMBOLOAD_POSTSTART         1199
#define IDC_SYMBOLLOAD_POSTSTART        1199
#define IDC_TURBOTYPE2                  1199
#define IDC_DIRECTSENSE                 1199
#define IDC_RESAMPLING                  1199
#define IDC_ANALOGCONTROLMODE           1199
#define IDC_VERSION2                    1199
#define IDC_TYPE_DYNAMIC                1200
#define IDC_PEAK_CONTROL                1200
#define IDC_MEMORY_TYPE                 1200
#define IDC_SYMBOLLOAD_POSTSTART2       1200
#define IDC_SCRIPTAUTOLOAD              1200
#define IDC_LUMA_RAMP3                  1200
#define IDC_PRESET                      1200
#define IDC_ASPECTRATIO                 1200
#define IDC_INPUTSOURCE                 1200
#define IDC_SIZE_SECTORS                1201
#define IDC_POWERUP_PATTERN             1201
#define IDC_U1MB_FLASH2                 1201
#define IDC_MAXFLASH8MB_FLASH           1201
#define IDC_FRAMESIZEMODE               1201
#define IDC_ANALOGCONTROLMODE2          1201
#define IDC_CONTROLLERPORT              1201
#define IDC_SIZE_MB                     1202
#define IDC_AXLON_RAMDISK               1202
#define IDC_GEOMETRY_AUTO               1203
#define IDC_COMBO7                      1203
#define IDC_HIGH_MEMORY                 1203
#define IDC_GEOMETRY_MANUAL             1204
#define IDC_HEADS                       1205
#define IDC_SPT                         1206
#define IDC_STATIC_SPT                  1207
#define IDC_STATIC_HEADS                1208
#define IDC_TYPE_DYNAMIC2               1209
#define IDC_TYPE_DIFFERENCING           1209
#define IDC_FONT_SEL                    1211
#define IDC_SIZE_SEL                    1212
#define IDC_SIZE_LIST                   1213
#define IDC_STATIC_SAMPLETEXT           1214
#define IDC_FONT_LIST                   1215
#define IDC_CHECK1                      1217
#define IDC_ENCODE_ALL_FRAMES           1217
#define IDC_QUICKMAP                    1217
#define IDC_ENDFUNCTION                 1217
#define IDC_VISIBLE                     1217
#define IDC_PAUSE_ON_MENU               1217
#define IDC_ENABLE_SDX                  1217
#define IDC_IGNORETHISTITLE             1217
#define IDC_16BIT                       1217
#define IDC_VBXE_SHAREDMEM              1217
#define IDC_TRACE_HISTORY               1217
#define IDC_AXLON_ALIASING              1217
#define IDC_FASTBOOT                    1217
#define IDC_CTIA                        1217
#define IDC_WARP                        1217
#define IDC_CUSTOM                      1217
#define IDC_AUTO_PROFILE                1217
#define IDC_SHOW_ALL                    1217
#define IDC_HWACCEL_SCREENFX            1217
#define IDC_ENABLE_BLOOM                1217
#define IDC_AUTOLOADOSSYMBOLS           1217
#define IDC_AUTOLOADSYSTEMSYMBOLS       1217
#define IDC_DEFAULTDD1                  1217
#define IDC_HOTRELOAD                   1217
#define IDC_LOCKHUESTART                1217
#define IDC_USERAWINPUT                 1217
#define IDC_RANDOMIZELAUNCHDELAY        1217
#define IDC_AUTOSPEED                   1217
#define IDC_ACTIVITYLED                 1217
#define IDC_AUTOCHECK                   1217
#define IDC_BOOLOPT                     1217
#define IDC_NOISE                       1217
#define IDC_CHECK                       1217
#define IDC_ENABLE_CONDITION            1217
#define IDC_ACCESS_NONE                 1218
#define IDC_WRITE_PROTECT               1218
#define IDC_CHECK2                      1218
#define IDC_IGNOREALL                   1218
#define IDC_TRACE_VIDEO                 1218
#define IDC_ENABLE_MAPRAM               1218
#define IDC_FASTFPMATH                  1218
#define IDC_INTERLACE                   1218
#define IDC_PAUSEWHENINACTIVE           1218
#define IDC_SHOW_ALL2                   1218
#define IDC_SHOW_DETAILS                1218
#define IDC_SCANLINECOMPENSATION        1218
#define IDC_PAUSE_ON_MENU2              1218
#define IDC_USE_DARK_THEME              1218
#define IDC_AUTOLOADOSROMSYMBOLS        1218
#define IDC_DEFAULTDD2                  1218
#define IDC_HIDETARGETPOINTER           1218
#define IDC_LOCKGAMMA                   1218
#define IDC_USERAWINPUT2                1218
#define IDC_IMMEDIATEPOTS               1218
#define IDC_ACTIVITYLED2                1218
#define IDC_ENABLESDX                   1218
#define IDC_RECOVERY                    1218
#define IDC_16BIT2                      1218
#define IDC_SEAMLESSCUSTOMREFRESH       1218
#define IDC_ACTION_STOP                 1218
#define IDC_ACCESS_HOSTONLY             1219
#define IDC_TRACE_VIDEO2                1219
#define IDC_TRACE_BASIC                 1219
#define IDC_WRITE_PROTECT2              1219
#define IDC_NVRAM_PROTECT               1219
#define IDC_ENABLE_FLOATINGIOBUS        1219
#define IDC_SIOPATCH_C                  1219
#define IDC_CTIA3                       1219
#define IDC_SCANLINES                   1219
#define IDC_DEFAULTDD3                  1219
#define IDC_CHECK3                      1219
#define IDC_AUTOHIDEPOINTER             1219
#define IDC_LOCKGAMMA2                  1219
#define IDC_NORMALIZECONTRAST           1219
#define IDC_ENABLEHDR                   1219
#define IDC_AUTOLOADOSROMSYMBOLS2       1219
#define IDC_DEBUGLINK                   1219
#define IDC_LOCKTOREFRESH               1219
#define IDC_ACTION_COMMAND              1219
#define IDC_ACCESS_NAT                  1220
#define IDC_TRACE_BASIC2                1220
#define IDC_LIMIT_MEMORY                1220
#define IDC_SIOPATCH_D                  1220
#define IDC_ENABLE_ULTIMATE1MB          1220
#define IDC_AUDIOMONITOR                1220
#define IDC_SCANLINES2                  1220
#define IDC_PERITEL                     1220
#define IDC_DEFAULTDD4                  1220
#define IDC_NORMALIZECONTRAST2          1220
#define IDC_IGNORENONHUE0LUMA           1220
#define IDC_HIDETARGETPOINTER2          1220
#define IDC_CONSTRAINFULLSCREEN         1220
#define IDC_ACTION_TRACE                1220
#define IDC_NETADDR                     1221
#define IDC_SIOPATCH_OTHER              1221
#define IDC_MUTEALL                     1221
#define IDC_ENABLE_ULTIMATE1MB2         1221
#define IDC_PRESERVEEXTRAM              1221
#define IDC_IGNORENONHUE0LUMA2          1221
#define IDC_OVERLAYCOMPUTEDCOLORS       1221
#define IDC_SHOWPADBOUNDS               1221
#define IDC_NETMASK                     1222
#define IDC_SIOBURST_D                  1222
#define IDC_AUDIO_CH1                   1222
#define IDC_SHOWPADPOINTERS             1222
#define IDC_STATIC_NETADDR              1223
#define IDC_SIOBURST_OTHER              1223
#define IDC_AUDIO_CH2                   1223
#define IDC_STATIC_NETMASK              1224
#define IDC_CIOPATCH_H                  1224
#define IDC_AUDIO_CH3                   1224
#define IDC_STATIC_BRIDGING             1225
#define IDC_CIOPATCH_P                  1225
#define IDC_AUDIO_CH4                   1225
#define IDC_ACCESS_VXLAN                1226
#define IDC_CIOPATCH_R                  1226
#define IDC_AUDIOMONITOR2               1226
#define IDC_AUDIOSCOPE                  1226
#define IDC_STATIC_TERMINAL_TYPE        1227
#define IDC_CIOPATCH_T                  1227
#define IDC_AUDIO_SCH1                  1227
#define IDC_COMBO2                      1228
#define IDC_SIOLEVEL                    1228
#define IDC_KEYMODE                     1228
#define IDC_CIOBURST                    1228
#define IDC_AUDIO_SCH2                  1228
#define IDC_TURBODECODER                1228
#define IDC_UPDATE_CHANNEL              1228
#define IDC_PEAK_IMAGE                  1229
#define IDC_SIOOVERRIDEDETECT           1229
#define IDC_AUDIO_SCH3                  1229
#define IDC_EDIT1                       1230
#define IDC_NAME                        1230
#define IDC_SCALE                       1230
#define IDC_FORWARDING_ADDRESS          1230
#define IDC_SEARCH                      1230
#define IDC_MAPPING                     1230
#define IDC_QUICKSEARCH                 1230
#define IDC_AUDIO_CH8                   1230
#define IDC_AUDIO_SCH4                  1230
#define IDC_SEED                        1230
#define IDC_LOCATION                    1230
#define IDC_TREE1                       1231
#define IDC_PROFILES                    1231
#define IDC_PAGE_TREE                   1231
#define IDC_EDIT3                       1231
#define IDC_COMMAND                     1231
#define IDC_BUTTON1                     1232
#define IDC_SCAN                        1232
#define IDC_EJECT                       1232
#define IDC_CUSTOMIZE                   1232
#define IDC_SWITCH                      1232
#define IDC_RESETALL                    1232
#define IDC_RECORD                      1232
#define IDC_ADDTITLE                    1232
#define IDC_UNMUTE_ALL                  1232
#define IDC_UNDISABLE                   1232
#define IDC_HOSTAUDIOOPTIONS            1232
#define IDC_FIRMWAREMANAGER             1232
#define IDC_ELEMENTS                    1232
#define IDC_TOGGLE_NTSC_PAL             1232
#define IDC_COPY                        1232
#define IDC_MATCH                       1232
#define IDC_EXPAND                      1232
#define IDC_USE_SEED                    1232
#define IDC_TRACE                       1232
#define IDC_DEFAULTAPPS                 1232
#define IDC_BUTTON2                     1233
#define IDC_REMOVE                      1233
#define IDC_COPY_TO_CUSTOM              1233
#define IDC_PLAY                        1233
#define IDC_DELETETITLE                 1233
#define IDC_AUTOADJUST                  1233
#define IDC_ENHTEXTFONT                 1233
#define IDC_SWITCH_TO_PORTABLE          1233
#define IDC_RESET_GAIN                  1233
#define IDC_BUTTON3                     1234
#define IDC_SETTINGS                    1234
#define IDC_SEEK_START                  1234
#define IDC_ADDALIAS                    1234
#define IDC_IGNORE                      1234
#define IDC_SWITCH_TO_REGISTRY          1234
#define IDC_CLEAR                       1235
#define IDC_REMOVEALL                   1235
#define IDC_SEEK_REWIND                 1235
#define IDC_DELETEALIAS                 1235
#define IDC_EDIT2                       1236
#define IDC_FORWARDING_PORT             1236
#define IDC_SEEK_FFWD                   1236
#define IDC_ADDTAG                      1236
#define IDC_CONDITION                   1236
#define IDC_OPTIONS                     1237
#define IDC_SEEK_END                    1237
#define IDC_DELETETAG                   1237
#define IDC_SETASDEFAULT                1238
#define IDC_SEEK_STOP                   1238
#define IDC_EDITALIAS                   1238
#define IDC_PAUSE                       1239
#define IDC_SETASDEFAULT2               1239
#define IDC_SETASSPECIFIC               1239
#define IDC_NTSC_LUMASHARP              1241
#define IDC_NTSC_PARAM1                 1241
#define IDC_SCANLINE_INTENSITY          1241
#define IDC_NTSC_CHROMASHARP            1242
#define IDC_NTSC_PARAM2                 1242
#define IDC_BLOOM_THRESHOLD             1242
#define IDC_NTSC_LUMANOTCHQ             1243
#define IDC_NTSC_PARAM3                 1243
#define IDC_BLOOM_RADIUS                1243
#define IDC_STATIC_NTSC_LUMANOTCHQ      1244
#define IDC_STATIC_NTSC_PARAM3          1244
#define IDC_BLOOM_DIRECT_INTENSITY      1244
#define IDC_STATIC_NTSC_CHROMASHARP     1245
#define IDC_STATIC_NTSC_PARAM2          1245
#define IDC_BLOOM_INDIRECT_INTENSITY    1245
#define IDC_STATIC_NTSC_LUMASHARP       1246
#define IDC_STATIC_NTSC_PARAM1          1246
#define IDC_STATIC_SCANLINE_INTENSITY   1246
#define IDC_NTSC_PARAM4                 1247
#define IDC_STATIC_BLOOM_THRESHOLD      1247
#define IDC_RICHEDIT                    1248
#define IDC_STATIC_NTSC_PARAM4          1248
#define IDC_STATIC_BLOOM_RADIUS         1248
#define IDC_NTSC_PARAM5                 1249
#define IDC_STATIC_BLOOM_DIRECT_INTENSITY 1249
#define IDC_STATIC_FORWARDING_ADDRESS   1250
#define IDC_STATIC_NTSC_PARAM5          1250
#define IDC_STATIC_BLOOM_INDIRECT_INTENSITY 1250
#define IDC_STATIC_FORWARDING_PORT      1251
#define IDC_NTSC_PARAM6                 1251
#define IDC_DISTORTION_X                1251
#define IDC_TUNNELADDR                  1252
#define IDC_STATIC_NTSC_PARAM6          1252
#define IDC_STATIC_DISTORTION_X         1252
#define IDC_STATIC_TUNNELADDR           1253
#define IDC_DISTORTION_Y                1253
#define IDC_STATIC_TUNNELPORTS          1254
#define IDC_STATIC_LSTICKAREA           1254
#define IDC_STATIC_DISTORTION_Y         1254
#define IDC_TUNNELSRCPORT               1255
#define IDC_ANALOG_DEAD_ZONE            1255
#define IDC_SDRBRIGHTNESS               1255
#define IDC_TUNNELTGTPORT               1256
#define IDC_DIGITAL_DEAD_ZONE           1256
#define IDC_HDRBRIGHTNESS               1256
#define IDC_STATIC_TUNNELSRCPORT        1257
#define IDC_ANALOG_POWER                1257
#define IDC_SDRBRIGHTNESS_VALUE         1257
#define IDC_STATIC_TUNNELTGTPORT        1258
#define IDC_STATIC_ANALOGDEADZONE       1258
#define IDC_STATIC_HDRBRIGHTNESS_VALUE  1258
#define IDC_HDRBRIGHTNESS_VALUE         1258
#define IDC_STATIC_ANALOGPOWER          1259
#define IDC_STATIC_DIGITALDEADZONE      1260
#define IDC_STATIC_RSTICKAREA           1261
#define IDC_STATIC_GAMEPAD              1261
#define IDC_STATIC_LTRIGAREA            1262
#define IDC_STATIC_RTRIGAREA            1263
#define IDC_TRIGGER_ANALOG_DEAD_ZONE    1264
#define IDC_STATIC_TRIGGERANALOGDEADZONE 1265
#define IDC_HOSTKEY_BINDINGS            1265
#define IDC_TRIGGER_ANALOG_POWER        1266
#define IDC_EMUKEY_LIST                 1266
#define IDC_STATIC_TRIGGERANALOGPOWER   1267
#define IDC_HOTKEY                      1267
#define IDC_TRIGGER_DIGITAL_DEAD_ZONE   1268
#define IDC_KEYMODE_CHAR                1268
#define IDC_STATIC_TRIGGERDIGITALDEADZONE 1269
#define IDC_KEYMODE_VK                  1269
#define IDC_STATIC_ARROWKEYMODE         1270
#define IDC_STATIC_ADDRESS2             1273
#define IDC_SETDEFAULT                  1274
#define IDC_CATEGORIES                  1275
#define IDC_STATIC_CATEGORIES           1276
#define IDC_HELP_TEXT                   1278
#define IDC_WRITEMODE                   1279
#define IDC_STEP_AREA                   1284
#define IDC_MESSAGE                     1285
#define IDD_WIZARD_MESSAGE              1285
#define IDD_WIZARD_FIRMWARE             1286
#define IDD_WIZARD_SELECTVIDEOTYPE      1287
#define IDD_WIZARD_EXPERIENCE           1288
#define IDC_TYPE_COMPUTER               1289
#define IDD_OPTIONS_DISPLAY_EFFECTS     1289
#define IDC_TYPE_5200                   1290
#define IDC_STEPS_LIST                  1290
#define IDD_DEVICE_KMKJZIDEV2           1290
#define IDD_OPTIONS_COMPAT              1291
#define IDC_TYPE_NTSC                   1291
#define IDD_DEVICE_COVOX                1292
#define IDC_TYPE_PAL                    1292
#define IDC_TYPE_STREAMLINED            1293
#define IDD_DEVICE_KMKJZIDEV3           1293
#define IDD_DEVICE_KMKJZIDE             1293
#define IDC_TYPE_AUTHENTIC              1294
#define IDD_DEVICE_ATR8000              1294
#define IDC_CHANNELS                    1295
#define IDD_DEVICE_PERCOMX              1295
#define IDD_DEVICE_PERCOMAT             1295
#define IDD_TRACEVIEWER_CHANNELS        1296
#define IDD_TRACEVIEWER_TIMESCALE       1297
#define IDD_TRACEVIEWER_EVENTS          1298
#define IDD_TRACEVIEWER_TIMESCALE1      1299
#define IDD_TRACEVIEWER_CPUHISTORY      1299
#define IDD_TRACEVIEWER_CPUHISTORY1     1300
#define IDD_TRACEVIEWER_CPUPROFILE      1300
#define IDD_CONFIGURE                   1301
#define IDC_TITLE_LIST                  1302
#define IDD_OPTIONS_DISPLAY1            1302
#define IDD_CONFIGURE_SYSTEM            1302
#define IDD_CONFIGURE_MEMORY            1303
#define IDC_ALIAS_LIST                  1304
#define IDD_CONFIGURE_ACCELERATION      1304
#define IDC_TAG_LIST                    1305
#define IDD_CONFIGURE_VIDEO             1305
#define IDC_LIST_ACTIVE                 1306
#define IDD_CONFIGURE_DISK              1306
#define IDC_LIST_AVAILABLE              1307
#define IDD_CONFIGURE_AUDIO             1307
#define IDD_CONFIGURE_CASSETTE          1308
#define IDD_CONFIGURE_CPU               1309
#define IDD_CONFIGURE_FIRMWARE          1310
#define IDD_CONFIGURE_DEVICES           1311
#define IDD_CONFIGURE_SPEED             1312
#define IDC_DIAGNOSIS                   1313
#define IDD_CONFIGURE_AUTORESET         1313
#define IDD_CONFIGURE_EASEOFUSE         1313
#define IDC_COMPAT_ENABLE               1314
#define IDD_CONFIGURE_SYSTEM1           1314
#define IDD_CONFIGURE_BOOT              1314
#define IDC_COMPAT_INTERNAL             1315
#define IDC_DRIVETYPE1                  1315
#define IDD_CONFIGURE_VIDEO1            1315
#define IDD_CONFIGURE_KEYBOARD          1315
#define IDC_COMPAT_EXTERNAL             1316
#define IDC_DRIVETYPE2                  1316
#define IDC_VBXEBASE_D600               1316
#define IDD_CONFIGURE_CAPTION           1316
#define IDC_DRIVETYPE3                  1317
#define IDC_RADIO2                      1317
#define IDC_VBXEBASE_D700               1317
#define IDC_SCROLLBAR1                  1317
#define IDC_HSCROLLBAR                  1317
#define IDD_CONFIGURE_DISK1             1317
#define IDD_CONFIGURE_DISPLAY           1317
#define IDC_LOCATION_READ               1317
#define IDC_DRIVETYPE4                  1318
#define IDC_CUSTOM1                     1318
#define IDC_TOOLBAR                     1318
#define IDD_CONFIGURE_DEBUGGER          1318
#define IDC_REFERENCE_IMAGE             1318
#define IDC_RADIO1                      1319
#define IDC_SIOACCEL_SIOV               1319
#define IDC_ENHTEXT_NONE                1319
#define IDD_ADJUST_SCREENFX             1319
#define IDC_INVERTMODE_ACCURATE         1319
#define IDC_LOCATION_PC                 1319
#define IDC_MODE_LISTEN                 1319
#define IDC_HARDWARE_TYPE               1320
#define IDC_SIOACCEL_PBI                1320
#define IDC_ENHTEXT_HW                  1320
#define IDD_CONFIGURE_SYSTEM2           1320
#define IDD_CONFIGURE_ASSESSMENT        1320
#define IDC_RADIO3                      1320
#define IDC_INVERTMODE_COMPATIBLE       1320
#define IDC_LOCATION_WRITE              1320
#define IDC_MODE_CONNECT                1320
#define IDC_VIDEO_STANDARD              1321
#define IDC_SIOACCEL_BOTH               1321
#define IDC_ENHTEXT_SW                  1321
#define IDD_CONFIGURE_OVERVIEW          1321
#define IDC_ARTIFACTMODE                1322
#define IDD_DEVICE_AMDC                 1322
#define IDC_FRAMEBLENDING               1323
#define IDD_DEVICE_CORVUS1              1323
#define IDD_DEVICE_XEP80                1323
#define IDC_ACCURATESECTORTIMING        1324
#define IDC_FRAMEBLENDING2              1324
#define IDC_FRAMEBLENDINGLINEAR         1324
#define IDD_DEVICE_DONGLE1              1324
#define IDD_DEVICE_CUSTOM               1324
#define IDC_SHOWSECTORCOUNTER           1325
#define IDC_STEREO                      1325
#define IDD_DEVICE_PERCOMRFD            1325
#define IDC_DRIVESOUNDS                 1326
#define IDC_NONLINEARMIXING             1326
#define IDD_CONFIGURE_DISPLAY1          1326
#define IDD_CONFIGURE_WORKAROUNDS       1326
#define IDC_SERIALNOISE                 1327
#define IDD_CONFIGURE_DISPLAY2          1327
#define IDD_CONFIGURE_UI                1327
#define IDC_AUTOBOOT                    1328
#define IDD_CONFIGURE_INPUT             1328
#define IDC_STEREO2                     1328
#define IDC_STEREOASMONO                1328
#define IDC_AUTOREWIND                  1329
#define IDD_DEVICE_DISKDRIVEFULL1       1329
#define IDD_DEVICE_HAPPY810             1329
#define IDC_SERIALNOISE2                1329
#define IDC_SPEAKERFILTER               1329
#define IDC_LOADDATAASAUDIO             1330
#define IDD_DEVICE_815                  1330
#define IDC_RANDOMIZESTARTPOS           1331
#define IDD_DEVICE_VIRTFAT32            1331
#define IDD_DEVICE_HDVIRTFAT32          1331
#define IDC_TURBOINVERT                 1332
#define IDD_DEVICE_PARFILEWRITER        1332
#define IDC_ENABLEBASIC                 1333
#define IDC_AUTOBOOT2                   1333
#define IDC_AUTOBASICBOOT               1333
#define IDD_DEVICE_COMPUTEREYES         1333
#define IDC_BASIC                       1334
#define IDC_TURBOINVERT2                1334
#define IDC_TURBOPREFILTER              1334
#define IDC_RANDOMIZESTARTPOS2          1334
#define IDC_VBIAVOIDANCE                1334
#define IDD_DEVICE_PARFILEWRITER1       1334
#define IDC_OS                          1335
#define IDD_CFGPROP_CHECKBOX            1335
#define IDC_RICHEDIT21                  1336
#define IDC_TEMPLATE                    1336
#define IDC_INFO                        1336
#define IDD_CFGPROP_SLIDER              1336
#define IDC_AUTORESET_CARTRIDGE         1337
#define IDD_CFGPROP_PATH1               1337
#define IDD_CFGPROP_TEXT                1337
#define IDC_AUTORESET_BASIC             1338
#define IDD_DEVICE_GENERIC              1338
#define IDC_AUTORESET_VIDEOSTD          1339
#define IDD_CFGPROP_PATH2               1339
#define IDD_CFGPROP_GENERIC             1339
#define IDC_BOOTUNLOAD_CARTRIDGES       1340
#define IDD_DBG_BREAKPOINTS1            1340
#define IDD_DBG_TARGETS                 1340
#define IDC_BOOTUNLOAD_DISKS            1341
#define IDD_DEVICE_1030MODEM1           1341
#define IDD_DEVICE_1400XL               1341
#define IDC_AUTORESET_VIDEOSTD4         1342
#define IDC_BOOTUNLOAD_TAPES            1342
#define IDD_DEVICE_NETSERIAL            1342
#define IDC_PROGRAMLOADMODE             1343
#define IDD_CONFIGURE_DEBUGGER1         1343
#define IDD_CONFIGURE_ACCESSIBILITY     1343
#define IDC_RICHEDIT22                  1344
#define IDC_CAPTION                     1344
#define IDC_COMMAND1                    1345
#define IDC_LIST2                       1346
#define IDC_STATIC_NONEFOUND            1347
#define IDC_STATIC_REGISTRY             1348
#define IDC_STATIC_PORTABLE             1349
#define IDC_STATIC_PORTABLE2            1350
#define IDC_STATIC_MIGRATING            1350
#define IDC_SHOW_INDICATORS             1350
#define IDC_PAD_INDICATORS              1351
#define IDC_WARNING                     1352
#define IDC_WARNING2                    1353
#define IDC_SYSLINK1                    1353
#define IDC_GAMMA_WARNING               1353
#define IDC_RSS_FEED                    1353
#define IDC_REFERENCE_VIEW              1354
#define IDC_LABEL_DISTORTION_X          1356
#define IDC_LABEL_DISTORTION_Y          1357
#define IDC_LABEL                       1358
#define IDC_LABEL_BLOOM_THRESHOLD       1358
#define IDC_LABEL_BLOOM_RADIUS          1359
#define IDC_LABEL_BLOOM_DIRECT_INTENSITY 1360
#define IDC_LABEL_BLOOM_INDIRECT_INTENSITY 1361
#define IDC_VIDEOBITRATE                1362
#define IDC_SLIDER2                     1363
#define IDC_AUDIOBITRATE                1363
#define IDC_SLIDER                      1363
#define IDC_VIDEOBITRATE_VALUE          1364
#define IDC_AUDIOBITRATE_VALUE          1365
#define IDC_STATIC_VIDEOBITRATE         1366
#define IDC_STATIC_AUDIOBITRATE         1367
#define IDC_SW7                         1368
#define IDC_SW8                         1369
#define IDC_JUMPER                      1370
#define IDC_CHECK4                      1371
#define IDC_DRIVE2                      1371
#define IDC_USESYSTEMSDR                1371
#define IDC_STATIC_QUICKSEARCH          1372
#define IDC_CHECK5                      1372
#define IDC_USESYSTEMHDR                1372
#define IDC_STATIC_ALIASES              1373
#define IDC_STATIC_TAGS                 1374
#define IDC_STATIC_SIGSINALIAS          1375
#define IDC_FDCTYPE                     1376
#define IDC_POLL_DIRECTORIES            1377
#define IDC_GAIN                        1378
#define IDC_STATIC_GAIN                 1379
#define IDC_COMBOBOXEX1                 1380
#define IDC_STATIC_DIVIDER              1381
#define IDC_AUTOHIDEMENU                1382
#define IDC_VARS                        1383
#define IDC_CURRENT_SEED                1385
#define IDC_NEXT_SEED                   1386
#define IDC_SLIDER1                     1387
#define IDC_AUTOSPEEDRATE               1387
#define IDC_STATIC_AUTOSPEEDRATE        1388
#define IDC_BASEADDRESS                 1389
#define IDC_STATIC_PARENT               1390
#define IDC_STATIC_SIZEMB               1391
#define IDC_STATIC_SIZESECTORS          1392
#define IDC_STATIC_GEOMETRY             1393
#define IDC_STATIC_SDRBRIGHTNESS        1394
#define IDC_STATIC_HDRBRIGHTNESS        1395
#define IDC_HDRWARNING                  1396
#define IDC_CUSTOM2                     1397
#define IDC_TEXTMODE                    1398
#define IDC_STATIC_VALUE                1399
#define IDC_STATIC_LAYOUTRECT           1400
#define IDC_BPS                         1401
#define IDC_RADIO4                      1402
#define IDC_LOCATION_CONDITION          1402
#define IDC_TARGETS                     1403
#define IDC_STATIC_MESSAGE              1404
#define IDC_LISTEN                      1405
#define IDC_FORCELOWERCASE              1406
#define IDC_STATIC_CHANNEL_SELECTOR     1407
#define IDC_STATIC_UPDATE_CHANNEL       1407
#define ID_FILTERMODE_POINT             40023
#define ID_FILTERMODE_BILINEAR          40024
#define ID_FILTERMODE_BICUBIC           40025
#define ID_DEBUG_RUN                    40055
#define ID_CONTEXT_GOTODISASSEMBLY      40103
#define ID_CONTEXT_SETNEXTSTATEMENT     40104
#define ID_CONTEXT_SHOWNEXTSTATEMENT    40138
#define ID_CONTEXT_TOGGLEBREAKPOINT     40139
#define ID_CONTEXT_GOTOSOURCE           40140
#define ID_COLORS_ALTERNATE             40218
#define ID_CONTEXT_CLEARALL             40226
#define ID_CONTEXT_TOGGLEREADBREAKPOINT 40227
#define ID_CONTEXT_TOGGLEWRITEBREAKPOINT 40228
#define ID_PROFMODE_SAMPLEINSNS         40244
#define ID_PROFMODE_SAMPLEFNS           40246
#define ID_PROFMODE_SAMPLEBASIC         40248
#define ID_HISTORYCONTEXTMENU_SHOWPCADDRESS 40306
#define ID_HISTORYCONTEXTMENU_SHOWREGISTERS 40307
#define ID_HISTORYCONTEXTMENU_SHOWFLAGS 40308
#define ID_HISTORYCONTEXTMENU_SHOWCODEBYTES 40309
#define ID_CONTEXT_SHOWCODEBYTES        40310
#define ID_CONTEXT_SHOWLABELS           40311
#define ID_HISTORYCONTEXTMENU_SHOWLABELS 40312
#define ID_COLORS_DEFAULTNTSC           40336
#define ID_DISKEXP_DELETE               40338
#define ID_DISKEXP_RENAME               40340
#define ID_HISTORYCONTEXTMENU_COPYVISIBLETOCLIPBOARD 40349
#define ID_CONTEXT_FORCEUPDATE          40382
#define ID_PALETTE_CURRENTREGISTERVALUES 40384
#define ID_PALETTE_ANALYSIS             40386
#define ID_PROFMODE_CALLGRAPH           40388
#define ID_COLORS_1XNTSC                40406
#define ID_HISTORYCONTEXTMENU_COLLAPSELOOPS 40420
#define ID_HISTORYCONTEXTMENU_COLLAPSECALLS 40421
#define ID_HISTORYCONTEXTMENU_COLLAPSEINTERRUPTS 40422
#define ID_HISTORYCONTEXTMENU_SHOWBEAMPOSITION 40423
#define ID_HISTORYCONTEXTMENU_SHOWUNHALTEDCYCLES 40426
#define ID_HISTORYCONTEXTMENU_SETTIMESTAMPORIGIN 40427
#define ID_HISTORYCONTEXTMENU_RESETTIMESTAMPORIGIN 40429
#define ID_HISTORYCONTEXTMENU_SHOWCYCLES 40430
#define ID_HISTORYCONTEXTMENU_SHOWMICROSECONDS 40431
#define ID_DISPLAYCONTEXTMENU_COPY      40445
#define ID_DISPLAYCONTEXTMENU_PASTE     40446
#define ID_HISTORYCONTEXTMENU_SHOWSPECIALREGISTERS 40477
#define ID_BOOTIMAGE                    40478
#define ID_DRAGDROP_BOOTIMAGE           40479
#define ID_MOUNTIMAGE_CARTRIDGE         40480
#define ID_MOUNTIMAGE_D1                40481
#define ID_MOUNTIMAGE_D2                40482
#define ID_MOUNTIMAGE_D3                40483
#define ID_MOUNTIMAGE_D4                40484
#define ID_MOUNTIMAGE_D                 40485
#define ID_CONTEXT_NEWDISK              40486
#define ID_CONTEXT_MOUNTFOLDERASVIRTUALDOS2DISK 40487
#define ID_CONTEXT_MOUNTFOLDERASVIRTUALSPARTADOSDISK 40488
#define ID_CONTEXT_EXPLOREDISK          40489
#define ID_CONTEXT_MOUNTFOLDERDOS2      40490
#define ID_CONTEXT_MOUNTFOLDERSDFS      40491
#define ID_CONTEXT_SAVEDISK             40492
#define ID_CONTEXT_EXTRACTBOOTSECTORSFORVIRTUALDOS2DISK 40493
#define ID_CONTEXT_EXTRACTBOOTSECTORS   40494
#define ID_MENU_CLEAR                   40495
#define ID_CONTEXT_CLEAR                40496
#define ID_HISTORYCONTEXTMENU_SHOWLABELNAMESPACES 40497
#define ID_CONTEXT_SWAPWITHANOTHERDRIVE 40498
#define ID_CONTEXTMENU_ALTIRRA2         40499
#define ID_CONTEXTMENU_DEFAULT          40502
#define ID_CONTEXT_VIEW                 40504
#define ID_DISKEXP_VIEW                 40505
#define ID_CONTEXT_NEWFOLDER            40506
#define ID_DISKEXP_NEWFOLDER            40507
#define ID_HISTORYCONTEXTMENU_GOTOSOURCE 40508
#define ID_CONTEXT_ROTATETOANOTHERDRIVE 40509
#define ID_MODEMENU_BASICBLOCKSAMPLING  40510
#define ID_PROFMODE_BASICBLOCK          40511
#define ID_COUNTERS_BRANCHTAKEN         40512
#define ID_COUNTERS_BRANCHNOTTAKEN      40513
#define ID_COUNTERS_PAGECROSSING        40514
#define ID_COUNTERS_REDUNDANTOPERATION  40515
#define ID_FRAMETRIGGERING_NOFRAMEBOUNARY 40516
#define ID_FRAMETRIGGERING_VERTICALBLANK 40517
#define ID_FRAMETRIGGER_PCADDRESS       40518
#define ID_FRAMETRIGGER_NONE            40519
#define ID_FRAMETRIGGER_VBLANK          40520
#define ID_COUNTER_BRANCHTAKEN          40521
#define ID_COUNTER_BRANCHNOTTAKEN       40522
#define ID_COUNTER_PAGECROSSING         40523
#define ID_COUNTER_REDUNDANTOPERATION   40524
#define ID_CONTEXT_RECURSIVELYEXPANDALL 40525
#define ID_CONTEXT_EXPANDARCS           40526
#define ID_CONTEXT_SAVEDISKAS           40527
#define ID_FILE_NEW                     40528
#define ID_FILE_LOAD                    40529
#define ID_FILE_SAVE                    40530
#define ID_FILE_EXIT                    40531
#define ID_BUILD_COMPILE                40532
#define ID_FILE_SAVEAS                  40533
#define ID_BUILD_COMPILETO              40538
#define ID_CONTEXTMENU_NTSCXL           40542
#define ID_LISTCONTEXTMENU_COPYAS       40544
#define ID_COPYASCSV                    40545
#define ID_TIMESTAMPFORMAT_SHOWTAPEPOSITION 40546
#define ID_HISTORYCONTEXTMENU_SHOWTAPEPOSITION 40547
#define ID_HISTORYCONTEXTMENU_SHOWTAPEPOSITIONSAMPLES 40548
#define ID_TIMESTAMPFORMAT_SHOWTAPEPOSITION40549 40549
#define ID_HISTORYCONTEXTMENU_SHOWTAPEPOSITIONSECONDS 40550
#define ID_CONTEXT_COPY                 40551
#define ID_CONTEXT_CHANGEINTERLEAVE     40552
#define ID_CHANGEINTERLEAVE_DEFAULT     40553
#define ID_CHANGEINTERLEAVE_9           40554
#define ID_CHANGEINTERLEAVE_10          40555
#define ID_CHANGEINTERLEAVE_13          40556
#define ID_CHANGEINTERLEAVE_15          40557
#define ID_CHANGEINTERLEAVE_12          40558
#define ID_CHANGEINTERLEAVE_1           40559
#define ID_CHANGEINTERLEAVE_11          40560
#define ID_CHANGEINTERLEAVE_5           40561
#define ID_CHANGEINTERLEAVE_7           40562
#define ID_CHANGEINTERLEAVE_8           40563
#define ID_CHANGEINTERLEAVE_1_1         40564
#define ID_CHANGEINTERLEAVE_9_1         40565
#define ID_CHANGEINTERLEAVE_9_1REV      40566
#define ID_CHANGEINTERLEAVE_SD_5_1      40567
#define ID_CHANGEINTERLEAVE_SD_9_1REV   40568
#define ID_CHANGEINTERLEAVE_SD_9_1      40569
#define ID_CHANGEINTERLEAVE_ED_13_1     40570
#define ID_CHANGEINTERLEAVE_13_1_REV    40571
#define ID_CHANGEINTERLEAVE_ED_7_1      40572
#define ID_CHANGEINTERLEAVE_DD_15_1     40573
#define ID_CHANGEINTERLEAVE_DD_9_1      40574
#define ID_CHANGEINTERLEAVE_DD_7_1      40575
#define ID_CHANGEINTERLEAVE_12_1        40576
#define ID_CHANGEINTERLEAVE_SD_9_1_REV  40577
#define ID_CHANGEINTERLEAVE_ED_12_1     40578
#define ID_CONTEXT_CONVERTTO            40579
#define ID_CONVERTTO_DOS2               40580
#define ID_CONVERTTO_MYDOS              40581
#define ID_CONVERTTO_SPARTADOS          40582
#define ID_CONVERTFILESYSTEM_DOS2       40583
#define ID_CONVERTFILESYSTEM_MYDOS      40584
#define ID_CONVERTFILESYSTEM_SPARTADOS  40585
#define ID_CONVERTFILESYSTEM_SPARTADOS40586 40586
#define ID_CONVERTFILESYSTEM_SPARTADOS_512 40587
#define ID_CONVERTTO_SPARTADOS_DD       40588
#define ID_CONVERTTO_SPARTADOS_SD       40589
#define ID_CONVERTTO_MYDOS_DD           40590
#define ID_CONVERTTO_MYDOS_SDED         40591
#define ID_CONVERTTO_DOS2_DD            40592
#define ID_CONVERTTO_DOS2_SDED          40593
#define ID_CONVERTTO_SPARTADOS_SDED     40594
#define ID_CONVERTTO_SPARTADOS_512      40595
#define ID_CHANGEINTERLEAVE_14          40596
#define ID_CHANGEINTERLEAVE_SD_12_1     40597
#define ID_CONVERTFILESYSTEM_DOS1       40598
#define ID_CONVERTTO_DOS1_SD            40599
#define ID_CONTEXT_REVERTDISK           40600
#define ID_FILE_OPENIMAGE               40601
#define ID_OPTIONS_NAMECHECKING         40602
#define ID_NAMECHECKING_STRICT          40603
#define ID_NAMECHECKING_RELAXED         40604
#define ID_FILENAMECHECKING_ALIASNON    40605
#define ID_ADJUST_FILENAMES             40606
#define ID_HISTORYCONTEXTMENU_SHOWGLOBALPCADDRESS 40607
#define ID_MENU_ENABLEGLOBALADDRESSES   40608
#define ID_CONTEXTMENU_NTSC800          40609
#define ID_COLORS_NTSC800               40610
#define ID_OPTIONS_COMMONPAL            40612
#define ID_OPTIONS_USESEPARATEPAL       40613
#define ID_OPTIONS_USEPALQUIRKS         40614
#define ID_OPTIONS_SHAREDPALETTES       40615
#define ID_OPTIONS_SEPARATEPALETTES     40616
#define ID_VIEW_SHOWRGBADJUSTMENTS      40617
#define ID_VIEW_SHOWRGBRELATIVEANGLES   40618
#define ID_VIEW_SHOWRGBSHIFTS           40619
#define ID_VIEW_SHOWRGBRELATIVEOFFSETS  40620
#define ID_CONTEXT_SHOWPROCEDUREBREAKS  40621
#define ID_CONTEXT_SHOWCALLPREVIEWS     40622
#define ID_CONTEXT_SHOWLABELNAMESPACES  40623
#define ID_DISKEXP_IMPORTFILE           40624
#define ID_DISKEXP_EXPORTFILE           40625
#define ID_FILE_EXPORTPALETTE           40628
#define ID_TOOLS_UPDATECHECKSUMSTOSHA256 40629
#define ID_FILE_IMPORTREFERENCEPICTURE  40630
#define ID_CONTEXT_ADDTOWATCH           40631
#define ID_CONTEXT_ADDTOON              40632
#define ID_CONTEXT_ADDTOSCREENWATCH     40633
#define ID_CONTEXT_ADDTOWATCHWINDOW     40634
#define ID_CONTEXT_SHOWINTERPRETATION   40635
#define ID_SHOWINTERPRETATION_NONE      40636
#define ID_SHOWINTERPRETATION_ATASCII   40637
#define ID_SHOWINTERPRETATION_INTERNAL  40638
#define ID_CONTEXT_INTERPRET_NONE       40639
#define ID_CONTEXT_INTERPRET_ATASCII    40640
#define ID_CONTEXT_INTERPRET_INTERNAL   40641
#define ID_CONTEXT_SHOWVALUESAS         40642
#define ID_SHOWVALUESAS_BYTES           40643
#define ID_SHOWVALUESAS_WORDS           40644
#define ID_SHOWVALUESAS_DECBYTES        40645
#define ID_SHOWVALUESAS_DECWORDS        40646
#define ID_SHOWVALUESAS_1               40647
#define ID_SHOWVALUESAS_2               40648
#define ID_SHOWVALUESAS_1BITFONT        40649
#define ID_SHOWVALUESAS_2BPPFONT        40650
#define ID_SHOWVALUESAS_1BPPFONT        40651
#define ID_CONTEXT_INTERPRET_1BPPFONT   40652
#define ID_CONTEXT_INTERPRET_2BPPFONT   40653
#define ID_INTERPRETAS_1                40654
#define ID_CONTEXT_INTERPRET_1BPPGFX    40655
#define ID_INTERPRETAS_2                40656
#define ID_INTERPRETAS_4                40657
#define ID_CONTEXT_INTERPRET_2BPPGFX    40658
#define ID_CONTEXT_INTERPRET_4BPPGFX    40659
#define ID_CONTEXT_RESETZOOM            40660
#define ID_CONTEXT_SHOWDISKFILEINEXPLORER 40661
#define ID_CONTEXT_IMPORTFILEASTEXT     40662
#define ID_CONTEXT_EXPORTFILEASTEXT     40663
#define ID_DISKEXP_IMPORTTEXT           40664
#define ID_DISKEXP_EXPORTTEXT           40665
#define ID_CONTEXT_65C816M              40666
#define ID_65C816M_AUTO                 40667
#define ID_65C816M_M8                   40668
#define ID_65C816M_M9                   40669
#define ID_65C816M_M16                  40670
#define ID_65C816M_M17                  40671
#define ID_65C816M_EMULATION            40672
#define ID_65C816M_M8X8                 40673
#define ID_65C816M_M8X16                40674
#define ID_65C816M_M16X8                40675
#define ID_65C816M_M16X16               40676
#define ID_65C816M_CURRENTCONTEXT       40677
#define ID_ASSIGNSHORTCUT               40679
#define ID_ASSIGNSHORTCUT_CONTEXTMENU   40680
#define ID_CONTEXTMENU                  40681
#define ID_EDIT_CUT                     40689
#define ID_EDIT_COPY                    40690
#define ID_EDIT_PASTE                   40691
#define ID_EDIT_DELETE                  40692
#define IDC_EDIT_PASTE                  40696
#define ID_EDIT_UNDO                    40697
#define ID_EDIT_REDO                    40698
#define ID_FILE_OPEN                    40703
#define ID_FILE_CLOSE                   40707
#define ID_FILE_EXPORTASCAS             40708
#define ID_FILE_EXPORTASWAV             40709
#define ID_FILE_SAVEASCAS               40710
#define ID_FILE_SAVEASWAV               40711
#define ID_EDIT_CONVERTTOSTANDARDBLOCK  40712
#define ID_EDIT_CONVERTTOFSKBLOCK       40713
#define ID_DATA_EXTRACTC                40714
#define ID_DATA_EXTRACTCFILE            40715
#define ID_MONITOR_CAPTURESIOTAPEDECODING 40716
#define ID_MONITOR_CAPTURESIO           40717
#define ID_VIEW_FSKDATA                 40718
#define ID_VIEW_TURBODATA               40719
#define ID_EDIT_CONVERTTORAWBLOCK       40720
#define ID_FILE_RELOAD                  40721
#define ID_VIEW_SHOWWAVEFORM            40724
#define ID_OPTIONS_KEEPWAVEFORMONLOAD   40725
#define ID_OPTIONS_STOREWAVEFORM        40726
#define ID_EDIT_REANALYZE               40727
#define ID_EDIT_REPEATLASTANALYSIS      40729
#define ID_EDIT_COPYDECODEDDATA         40730
#define ID_INTERPRETAS_8                40733
#define ID_CONTEXT_INTERPRET_8BPPGFX    40734
#define ID_BREAKPOINT_DELETE            40735
#define ID_BREAKPOINT_NEWBREAKPOINT     40736
#define ID_BREAKPOINT_NEW               40737
#define ID_FILE_EXPORT                  40738
#define ID_EXPORT_CHROMETRACEFORMAT     40739
#define ID_EXPORT_CHROMETRACE           40740
#define ID_PARTITION_OPEN               40741
#define ID_PARTITION_IMPORTDISKIMAGE    40742
#define ID_PARTITION_EXPORTDISKIMAGE    40743
#define ID_PARTITION_IMPORT             40744
#define ID_PARTITION_EXPORT             40745
#define ID_CONTEXT_SHOWMIXEDSOURCE      40746
#define ID_DISPLAYCONTEXTMENU_COPYESCAPEDTEXT 40747
#define ID_DISPLAYCONTEXTMENU_COPYHEX   40748
#define ID_DISPLAYCONTEXTMENU_COPYUNICODE 40749
#define ID_CONTEXT_USEDPREGISTERSTATE   40750
#define ID_CHANGEINTERLEAVE_2           40751
#define ID_CHANGEINTERLEAVE_SD_2_1      40752
#define ID_COPY                         40753
#define ID_PASTE                        40755
#define ID_TOOLS_VIEWMEMORYSTATISTICS   40756
#define ID_FILE_LOAD40757               40757
#define ID_FILE_SAVE40758               40758
#define ID_CONTEXT_OPENINDEFAULTEDITOR  40759
#define ID_CONTEXT_OPENIN               40760
#define ID_OPENIN_FILEEXPLORER          40761
#define ID_OPENIN_DEFAULTEDITOR         40762
#define ID_FILE_IMPORT                  40763
#define ID_IMPORT_ATARI800WINPLUS4      40764
#define ID_IMPORT_ATARI800              40765
#define ID_INPUT_PORT1_NONE             45000
#define ID_INPUT_PORT2_NONE             45100
#define ID_INPUT_PORT3_NONE             45200
#define ID_INPUT_PORT4_NONE             45300
#define ID_FILE_MRU_BASE                46000
#define ID_DYNAMIC_BASE                 47000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         40766
#define _APS_NEXT_CONTROL_VALUE         1408
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
