// Generated by Asuka from D:\p4root\Altirra\dev\src\VDDisplay\shaders\displayd3d9.fx. DO NOT EDIT.

struct TextureBinding {
	uint8 mStage;
	uint8 mTexture;
	bool mbWrapU;
	bool mbWrapV;
	bool mbBilinear;
};

struct PassInfo {
	int mVertexShaderIndex;
	int mPixelShaderIndex;
	const vdvector_view<const TextureBinding> mTextureBindings;
	int mRenderTarget;
	uint8 mViewportW;
	uint8 mViewportH;
	uint8 mBumpEnvScale;
	bool mbClipPosition;
};

struct TechniqueInfo {
	const vdvector_view<const PassInfo> mPasses;
};
static const TextureBinding g_technique_boxlinear_1_1_pass_0_texbindings[]={
	{ 0, 14, false, false, false },
	{ 1, 1, false, false, true },
};
static const PassInfo g_technique_boxlinear_1_1_passes[] = {
		{
			0, 0,
			g_technique_boxlinear_1_1_pass_0_texbindings,
			0,
			2, 2,
			true,
			false,
		},
};
extern const TechniqueInfo g_technique_boxlinear_1_1= {
	g_technique_boxlinear_1_1_passes,
};
static const TextureBinding g_technique_pal8_to_rgb_1_1_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 2, 6, false, false, false },
};
static const PassInfo g_technique_pal8_to_rgb_1_1_passes[] = {
		{
			1, 1,
			g_technique_pal8_to_rgb_1_1_pass_0_texbindings,
			0,
			3, 3,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_pal8_to_rgb_1_1= {
	g_technique_pal8_to_rgb_1_1_passes,
};
static const TextureBinding g_technique_point_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 1, 11, true, true, false },
};
static const PassInfo g_technique_point_2_0_passes[] = {
		{
			2, 2,
			g_technique_point_2_0_pass_0_texbindings,
			0,
			2, 2,
			false,
			true,
		},
};
extern const TechniqueInfo g_technique_point_2_0= {
	g_technique_point_2_0_passes,
};
static const TextureBinding g_technique_bilinear_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, true },
	{ 1, 11, true, true, false },
};
static const PassInfo g_technique_bilinear_2_0_passes[] = {
		{
			2, 2,
			g_technique_bilinear_2_0_pass_0_texbindings,
			0,
			2, 2,
			false,
			true,
		},
};
extern const TechniqueInfo g_technique_bilinear_2_0= {
	g_technique_bilinear_2_0_passes,
};
static const TextureBinding g_technique_boxlinear_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, true },
};
static const PassInfo g_technique_boxlinear_2_0_passes[] = {
		{
			3, 3,
			g_technique_boxlinear_2_0_pass_0_texbindings,
			0,
			2, 2,
			false,
			true,
		},
};
extern const TechniqueInfo g_technique_boxlinear_2_0= {
	g_technique_boxlinear_2_0_passes,
};
static const TextureBinding g_technique_bicubic_2_0_pass_0_texbindings[]={
	{ 0, 12, true, false, false },
	{ 1, 1, false, false, false },
	{ 2, 1, false, false, true },
};
static const TextureBinding g_technique_bicubic_2_0_pass_1_texbindings[]={
	{ 0, 13, true, false, false },
	{ 1, 7, false, false, false },
	{ 2, 7, false, false, true },
};
static const PassInfo g_technique_bicubic_2_0_passes[] = {
		{
			4, 4,
			g_technique_bicubic_2_0_pass_0_texbindings,
			1,
			2, 1,
			false,
			false,
		},
		{
			5, 4,
			g_technique_bicubic_2_0_pass_1_texbindings,
			0,
			2, 2,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_bicubic_2_0= {
	g_technique_bicubic_2_0_passes,
};
static const TextureBinding g_technique_bicubic_2_0_dither_pass_0_texbindings[]={
	{ 0, 12, true, false, false },
	{ 1, 1, false, false, false },
	{ 2, 1, false, false, true },
};
static const TextureBinding g_technique_bicubic_2_0_dither_pass_1_texbindings[]={
	{ 0, 13, true, false, false },
	{ 1, 7, false, false, false },
	{ 2, 7, false, false, true },
	{ 3, 11, true, true, false },
};
static const PassInfo g_technique_bicubic_2_0_dither_passes[] = {
		{
			4, 4,
			g_technique_bicubic_2_0_dither_pass_0_texbindings,
			1,
			2, 1,
			false,
			false,
		},
		{
			5, 5,
			g_technique_bicubic_2_0_dither_pass_1_texbindings,
			0,
			2, 2,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_bicubic_2_0_dither= {
	g_technique_bicubic_2_0_dither_passes,
};
static const TextureBinding g_technique_ycbcr_601_to_rgb_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 1, 2, false, false, true },
	{ 2, 3, false, false, true },
};
static const PassInfo g_technique_ycbcr_601_to_rgb_2_0_passes[] = {
		{
			6, 6,
			g_technique_ycbcr_601_to_rgb_2_0_pass_0_texbindings,
			0,
			3, 3,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_ycbcr_601_to_rgb_2_0= {
	g_technique_ycbcr_601_to_rgb_2_0_passes,
};
static const TextureBinding g_technique_ycbcr_709_to_rgb_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 1, 2, false, false, true },
	{ 2, 3, false, false, true },
};
static const PassInfo g_technique_ycbcr_709_to_rgb_2_0_passes[] = {
		{
			6, 6,
			g_technique_ycbcr_709_to_rgb_2_0_pass_0_texbindings,
			0,
			3, 3,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_ycbcr_709_to_rgb_2_0= {
	g_technique_ycbcr_709_to_rgb_2_0_passes,
};
static const TextureBinding g_technique_ycbcr_601fr_to_rgb_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 1, 2, false, false, true },
	{ 2, 3, false, false, true },
};
static const PassInfo g_technique_ycbcr_601fr_to_rgb_2_0_passes[] = {
		{
			6, 7,
			g_technique_ycbcr_601fr_to_rgb_2_0_pass_0_texbindings,
			0,
			3, 3,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_ycbcr_601fr_to_rgb_2_0= {
	g_technique_ycbcr_601fr_to_rgb_2_0_passes,
};
static const TextureBinding g_technique_ycbcr_709fr_to_rgb_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 1, 2, false, false, true },
	{ 2, 3, false, false, true },
};
static const PassInfo g_technique_ycbcr_709fr_to_rgb_2_0_passes[] = {
		{
			6, 8,
			g_technique_ycbcr_709fr_to_rgb_2_0_pass_0_texbindings,
			0,
			3, 3,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_ycbcr_709fr_to_rgb_2_0= {
	g_technique_ycbcr_709fr_to_rgb_2_0_passes,
};
static const TextureBinding g_technique_pal8_to_rgb_2_0_pass_0_texbindings[]={
	{ 0, 1, false, false, false },
	{ 1, 6, false, false, false },
};
static const PassInfo g_technique_pal8_to_rgb_2_0_passes[] = {
		{
			7, 9,
			g_technique_pal8_to_rgb_2_0_pass_0_texbindings,
			0,
			3, 3,
			false,
			false,
		},
};
extern const TechniqueInfo g_technique_pal8_to_rgb_2_0= {
	g_technique_pal8_to_rgb_2_0_passes,
};

struct EffectInfo {
	const vdvector_view<const uint32> mShaderData;
	const vdvector_view<const uint32> mVertexShaderOffsets;
	const vdvector_view<const uint32> mPixelShaderOffsets;
};
static const uint32 g_effect_shaderData[]={
		0xfffe0101,0x00000051,0xa00f0001,0x00000000,0x00000000,0x00000000,0x00000000,0x0000001f,
		0x80000000,0x900f0000,0x0000001f,0x80000005,0x900f0001,0x0000001f,0x80010005,0x900f0002,
		0x00000005,0x80030000,0x90e40002,0xa0e40000,0x00000005,0xe0030000,0x80e40000,0xa0eb0007,
		0x00000001,0x80010000,0xa0000001,0x00000001,0x80020001,0xa0550008,0x00000005,0x80020000,
		0x80550001,0xa0aa0002,0x00000002,0xe0030001,0x80e40000,0x90e40001,0x00000001,0xc00f0000,
		0x90e40000,0x0000ffff,0xfffe0101,0x00000051,0xa00f0000,0x00000000,0x3f7fc000,0x00000000,
		0x00000000,0x0000001f,0x80000000,0x900f0000,0x0000001f,0x80000005,0x900f0001,0x00000001,
		0xc00f0000,0x90e40000,0x00000001,0xe0030000,0x90e40001,0x00000001,0xe0070001,0xa0c40000,
		0x00000001,0xe0070002,0xa0000000,0x0000ffff,0xfffe0200,0x05000051,0xa00f0001,0x3d800000,
		0x00000000,0x00000000,0x00000000,0x0200001f,0x80000000,0x900f0000,0x0200001f,0x80000005,
		0x900f0001,0x0200001f,0x80010005,0x900f0002,0x03000005,0x80030000,0x90e40002,0xa0e40000,
		0x03000005,0xe0030001,0x80e40000,0xa0000001,0x02000001,0xc00f0000,0x90e40000,0x02000001,
		0xe0030000,0x90e40001,0x0000ffff,0xfffe0200,0x0200001f,0x80000000,0x900f0000,0x0200001f,
		0x80010005,0x900f0001,0x03000005,0xe0030000,0x90e40001,0xa0e40001,0x02000001,0xc00f0000,
		0x90e40000,0x0000ffff,0xfffe0200,0x05000051,0xa00f0001,0x00000000,0x3f800000,0xbfc00000,
		0x3fc00000,0x0200001f,0x80000000,0x900f0000,0x0200001f,0x80000005,0x900f0001,0x0200001f,
		0x80010005,0x900f0002,0x03000005,0x80010000,0x90000002,0xa0000000,0x03000005,0xe0010000,
		0x80000000,0xa0ff0005,0x02000001,0x800f0000,0xa0e40001,0x04000004,0x80030001,0xa0550008,
		0x80e40000,0x80e20000,0x04000004,0xe0030001,0x80e40001,0xa0eb0002,0x90e40001,0x03000005,
		0x80030001,0x80e40000,0xa0550008,0x04000004,0xe0030002,0x80e40001,0xa0eb0002,0x90e40001,
		0x04000004,0x80030000,0xa0550008,0x80e40000,0x80e30000,0x04000004,0xe0030003,0x80e40000,
		0xa0eb0002,0x90e40001,0x02000001,0xc00f0000,0x90e40000,0x02000001,0xe0020000,0xa0000001,
		0x0000ffff,0xfffe0200,0x05000051,0xa00f0002,0x00000000,0xbfc00000,0x3fc00000,0x3d800000,
		0x0200001f,0x80000000,0x900f0000,0x0200001f,0x80010005,0x900f0001,0x03000005,0x80070000,
		0x90d10001,0xa0d10000,0x03000005,0xe0010000,0x80000000,0xa0ff0006,0x03000005,0xe0030004,
		0x80e90000,0xa0ff0002,0x02000001,0x800c0000,0xa0e40004,0x03000005,0x800f0000,0x80bb0000,
		0xa0840002,0x03000005,0x80010001,0x90000001,0xa0000000,0x03000005,0x80020001,0x90550001,
		0xa0550001,0x04000004,0xe0030001,0x80e40001,0xa0eb0004,0x80e40000,0x04000004,0xe0030003,
		0x80e40001,0xa0eb0004,0x80ee0000,0x03000005,0x80030000,0x80e40001,0xa0eb0004,0x02000001,
		0xe0030002,0x80e40000,0x02000001,0xc00f0000,0x90e40000,0x02000001,0xe0020000,0xa0000002,
		0x0000ffff,0xfffe0200,0x0200001f,0x80000000,0x900f0000,0x0200001f,0x80000005,0x900f0001,
		0x0200001f,0x80010005,0x900f0002,0x03000005,0x80030000,0x90e40002,0xa0e40009,0x02000001,
		0x80030001,0xa0e40001,0x04000004,0x80030000,0x80e40000,0x80e40001,0xa0e4000a,0x03000005,
		0xe0030001,0x80e40000,0xa0eb0003,0x02000001,0xc00f0000,0x90e40000,0x02000001,0xe0030000,
		0x90e40001,0x0000ffff,0xfffe0200,0x0200001f,0x80000000,0x900f0000,0x0200001f,0x80000005,
		0x900f0001,0x02000001,0xc00f0000,0x90e40000,0x02000001,0xe0030000,0x90e40001,0x0000ffff,
		0xffff0101,0x00000042,0xb00f0000,0x00000043,0xb00f0001,0xb0e40000,0x00000001,0x800f0000,
		0xb0e40001,0x0000ffff,0xffff0101,0x00000042,0xb00f0000,0x00000047,0xb00f0001,0xb0e40000,
		0x00000048,0xb00f0002,0xb0e40000,0x00000001,0x800f0000,0xb0e40002,0x0000ffff,0xffff0200,
		0x05000051,0xa00f0000,0x3f7efeff,0x00000000,0x3b800000,0x00000000,0x0200001f,0x80000000,
		0xb0030000,0x0200001f,0x80000000,0xb0030001,0x0200001f,0x90000000,0xa00f0800,0x0200001f,
		0x90000000,0xa00f0801,0x03000042,0x800f0000,0xb0e40000,0xa0e40800,0x03000042,0x800f0001,
		0xb0e40001,0xa0e40801,0x03000005,0x80070000,0x80e40000,0xa0000000,0x02000001,0x80080000,
		0xa0550000,0x04000004,0x800f0000,0x80e40001,0xa0aa0000,0x80e40000,0x02000001,0x800f0800,
		0x80e40000,0x0000ffff,0xffff0200,0x05000051,0xa00f0000,0x3f000000,0x00000000,0x00000000,
		0x00000000,0x0200001f,0x80000000,0xb0030000,0x0200001f,0x90000000,0xa00f0800,0x03000002,
		0x80030000,0xb0e40000,0xa0000000,0x02000013,0x800c0000,0x801b0000,0x03000002,0x80030000,
		0x811b0000,0x80e40000,0x03000002,0x800c0000,0x801b0000,0xb11b0000,0x02000001,0x80080001,
		0xa0000000,0x04000004,0x801c0000,0x80e40000,0xa01b000b,0x80ff0001,0x03000002,0x80030000,
		0x811b0000,0x80e40000,0x03000002,0x80030000,0x80e40000,0xa0000000,0x03000005,0x80030000,
		0x80e40000,0xa01b0002,0x03000042,0x800f0000,0x80e40000,0xa0e40800,0x02000001,0x800f0800,
		0x80e40000,0x0000ffff,0xffff0200,0x05000051,0xa00f0000,0x00000000,0x00000000,0x00000000,
		0x00000000,0x0200001f,0x80000000,0xb0030000,0x0200001f,0x80000000,0xb0030001,0x0200001f,
		0x80000000,0xb0030002,0x0200001f,0x80000000,0xb0030003,0x0200001f,0x90000000,0xa00f0800,
		0x0200001f,0x90000000,0xa00f0801,0x0200001f,0x90000000,0xa00f0802,0x03000042,0x800f0000,
		0xb0e40001,0xa0e40801,0x03000042,0x800f0001,0xb0e40003,0xa0e40801,0x03000042,0x800f0002,
		0xb0e40000,0xa0e40800,0x03000042,0x800f0003,0xb0e40002,0xa0e40802,0x03000042,0x800f0004,
		0xb0e40002,0xa0e40801,0x04000012,0x80070005,0x80aa0002,0x80e40000,0x80e40001,0x04000012,
		0x80070000,0x80550002,0x80e40003,0x80e40004,0x03000002,0x80070001,0x81e40005,0x80e40000,
		0x04000004,0x80070000,0x80e40001,0x80000002,0x80e40000,0x02000001,0x80080000,0xa0000000,
		0x02000001,0x800f0800,0x80e40000,0x0000ffff,0xffff0200,0x05000051,0xa00f0000,0x3f7efeff,
		0x00000000,0x3b800000,0x00000000,0x0200001f,0x80000000,0xb0030000,0x0200001f,0x80000000,
		0xb0030001,0x0200001f,0x80000000,0xb0030002,0x0200001f,0x80000000,0xb0030003,0x0200001f,
		0x80000000,0xb0030004,0x0200001f,0x90000000,0xa00f0800,0x0200001f,0x90000000,0xa00f0801,
		0x0200001f,0x90000000,0xa00f0802,0x0200001f,0x90000000,0xa00f0803,0x03000042,0x800f0000,
		0xb0e40001,0xa0e40801,0x03000042,0x800f0001,0xb0e40003,0xa0e40801,0x03000042,0x800f0002,
		0xb0e40000,0xa0e40800,0x03000042,0x800f0003,0xb0e40002,0xa0e40802,0x03000042,0x800f0004,
		0xb0e40002,0xa0e40801,0x03000042,0x800f0005,0xb0e40004,0xa0e40803,0x04000012,0x80070006,
		0x80aa0002,0x80e40000,0x80e40001,0x04000012,0x80070000,0x80550002,0x80e40003,0x80e40004,
		0x03000002,0x80070001,0x81e40006,0x80e40000,0x04000004,0x80070000,0x80e40001,0x80000002,
		0x80e40000,0x03000005,0x80070000,0x80e40000,0xa0000000,0x02000001,0x80080000,0xa0550000,
		0x04000004,0x800f0000,0x80e40005,0xa0aa0000,0x80e40000,0x02000001,0x800f0800,0x80e40000,
		0x0000ffff,0xffff0200,0x05000051,0xa00f0000,0x3f94fdf4,0x00000000,0xbf5020c5,0x3fcc49ba,
		0x05000051,0xa00f0001,0xbf5fc942,0x3f0804f3,0xbf8b01ca,0x00000000,0x05000051,0xa00f0002,
		0x00000000,0xbec83127,0x400126e9,0x00000000,0x0200001f,0x80000000,0xb0030000,0x0200001f,
		0x80000000,0xb0030001,0x0200001f,0x90000000,0xa00f0800,0x0200001f,0x90000000,0xa00f0801,
		0x0200001f,0x90000000,0xa00f0802,0x03000042,0x800f0000,0xb0e40001,0xa0e40802,0x03000042,
		0x800f0001,0xb0e40000,0xa0e40800,0x03000042,0x800f0002,0xb0e40001,0xa0e40801,0x03000005,
		0x80080001,0x80aa0001,0xa0000000,0x04000004,0x80070000,0x80aa0000,0xa01b0000,0x80ff0001,
		0x04000004,0x80070000,0x80aa0002,0xa0e40002,0x80e40000,0x03000002,0x80070001,0x80e40000,
		0xa0e40001,0x02000001,0x800f0800,0x80e40001,0x0000ffff,0xffff0200,0x05000051,0xa00f0000,
		0xbf3428e5,0x3f07fd77,0xbf63b49a,0x00000000,0x05000051,0xa00f0001,0x00000000,0xbeb032a2,
		0x3fe2d0e5,0x00000000,0x05000051,0xa00f0002,0x3fb374bc,0xbf36d1a3,0x00000000,0x00000000,
		0x0200001f,0x80000000,0xb0030000,0x0200001f,0x80000000,0xb0030001,0x0200001f,0x90000000,
		0xa00f0800,0x0200001f,0x90000000,0xa00f0801,0x0200001f,0x90000000,0xa00f0802,0x03000042,
		0x800f0000,0xb0e40001,0xa0e40801,0x03000042,0x800f0001,0xb0e40001,0xa0e40802,0x03000042,
		0x800f0002,0xb0e40000,0xa0e40800,0x04000004,0x80070001,0x80aa0001,0xa0e40002,0x80aa0002,
		0x02000001,0x80080002,0x80aa0002,0x04000004,0x80070000,0x80aa0000,0xa0e40001,0x80e40001,
		0x03000002,0x80070002,0x80e40000,0xa0e40000,0x02000001,0x800f0800,0x80e40002,0x0000ffff,
		0xffff0200,0x05000051,0xa00f0000,0xbf4a5d69,0x3ea873ef,0xbf6e72c0,0x00000000,0x05000051,
		0xa00f0001,0x00000000,0xbe3fd1f1,0x3fed844d,0x00000000,0x05000051,0xa00f0002,0x3fc9930c,
		0xbeefadfd,0x00000000,0x00000000,0x0200001f,0x80000000,0xb0030000,0x0200001f,0x80000000,
		0xb0030001,0x0200001f,0x90000000,0xa00f0800,0x0200001f,0x90000000,0xa00f0801,0x0200001f,
		0x90000000,0xa00f0802,0x03000042,0x800f0000,0xb0e40001,0xa0e40801,0x03000042,0x800f0001,
		0xb0e40001,0xa0e40802,0x03000042,0x800f0002,0xb0e40000,0xa0e40800,0x04000004,0x80070001,
		0x80aa0001,0xa0e40002,0x80aa0002,0x02000001,0x80080002,0x80aa0002,0x04000004,0x80070000,
		0x80aa0000,0xa0e40001,0x80e40001,0x03000002,0x80070002,0x80e40000,0xa0e40000,0x02000001,
		0x800f0800,0x80e40002,0x0000ffff,0xffff0200,0x05000051,0xa00f0000,0x3f7f0000,0x3b000000,
		0x00000000,0x00000000,0x0200001f,0x80000000,0xb0030000,0x0200001f,0x90000000,0xa00f0800,
		0x0200001f,0x90000000,0xa00f0801,0x03000042,0x802f0000,0xb0e40000,0xa0e40800,0x04000004,
		0x80210000,0x80000000,0xa0000000,0xa0550000,0x02000001,0x80220000,0xa0aa0000,0x03000042,
		0x800f0000,0x80e40000,0xa0e40801,0x02000001,0x800f0800,0x80e40000,0x0000ffff,
};
static const uint32 g_effect_vsOffsets[]={
0,42,68,99,114,177,241,274,288,};
static const uint32 g_effect_psOffsets[]={
288,298,311,354,410,484,577,645,712,779,815,};
static const EffectInfo g_effect={
	g_effect_shaderData,
	g_effect_vsOffsets,
	g_effect_psOffsets,
};
